"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.date_components import DateComponents
globals()['DateComponents'] = DateComponents
from elavon.model.additional_site_survey_info import AdditionalSiteSurveyInfo


class TestAdditionalSiteSurveyInfo(unittest.TestCase):
    """AdditionalSiteSurveyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdditionalSiteSurveyInfo(self):
        """Test AdditionalSiteSurveyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdditionalSiteSurveyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
