"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.scarecrow_application import ScarecrowApplication
globals()['ScarecrowApplication'] = ScarecrowApplication
from elavon.model.eframe_request_params import EframeRequestParams


class TestEframeRequestParams(unittest.TestCase):
    """EframeRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEframeRequestParams(self):
        """Test EframeRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EframeRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
