"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.address import Address
from elavon.model.credit_decision_info import CreditDecisionInfo
from elavon.model.date_components import DateComponents
from elavon.model.hemp_grower_info import HempGrowerInfo
from elavon.model.pci_info import PCIInfo
from elavon.model.vat_info import VatInfo
from elavon.model.verification_info import VerificationInfo
globals()['Address'] = Address
globals()['CreditDecisionInfo'] = CreditDecisionInfo
globals()['DateComponents'] = DateComponents
globals()['HempGrowerInfo'] = HempGrowerInfo
globals()['PCIInfo'] = PCIInfo
globals()['VatInfo'] = VatInfo
globals()['VerificationInfo'] = VerificationInfo
from elavon.model.business_info import BusinessInfo


class TestBusinessInfo(unittest.TestCase):
    """BusinessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessInfo(self):
        """Test BusinessInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BusinessInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
