"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.company_info_bundle import CompanyInfoBundle
from elavon.model.timings import Timings
globals()['CompanyInfoBundle'] = CompanyInfoBundle
globals()['Timings'] = Timings
from elavon.model.company_info_response import CompanyInfoResponse


class TestCompanyInfoResponse(unittest.TestCase):
    """CompanyInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyInfoResponse(self):
        """Test CompanyInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompanyInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
