"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.acting_intermediary_info import ActingIntermediaryInfo
from elavon.model.additional_auth_pricing_program_info import AdditionalAuthPricingProgramInfo
from elavon.model.additional_business_info import AdditionalBusinessInfo
from elavon.model.additional_card_pricing_info import AdditionalCardPricingInfo
from elavon.model.additional_description_info import AdditionalDescriptionInfo
from elavon.model.additional_lease_info import AdditionalLeaseInfo
from elavon.model.additional_site_survey_info import AdditionalSiteSurveyInfo
from elavon.model.bank_account_additional_info import BankAccountAdditionalInfo
from elavon.model.card_volume import CardVolume
from elavon.model.integrator_solution_info import IntegratorSolutionInfo
from elavon.model.provider_info import ProviderInfo
from elavon.model.sales_office_contact import SalesOfficeContact
from elavon.model.sales_person_contact import SalesPersonContact
from elavon.model.scarecrow_application import ScarecrowApplication
from elavon.model.value_added_services import ValueAddedServices
from elavon.model.var_other_details import VarOtherDetails
globals()['ActingIntermediaryInfo'] = ActingIntermediaryInfo
globals()['AdditionalAuthPricingProgramInfo'] = AdditionalAuthPricingProgramInfo
globals()['AdditionalBusinessInfo'] = AdditionalBusinessInfo
globals()['AdditionalCardPricingInfo'] = AdditionalCardPricingInfo
globals()['AdditionalDescriptionInfo'] = AdditionalDescriptionInfo
globals()['AdditionalLeaseInfo'] = AdditionalLeaseInfo
globals()['AdditionalSiteSurveyInfo'] = AdditionalSiteSurveyInfo
globals()['BankAccountAdditionalInfo'] = BankAccountAdditionalInfo
globals()['CardVolume'] = CardVolume
globals()['IntegratorSolutionInfo'] = IntegratorSolutionInfo
globals()['ProviderInfo'] = ProviderInfo
globals()['SalesOfficeContact'] = SalesOfficeContact
globals()['SalesPersonContact'] = SalesPersonContact
globals()['ScarecrowApplication'] = ScarecrowApplication
globals()['ValueAddedServices'] = ValueAddedServices
globals()['VarOtherDetails'] = VarOtherDetails
from elavon.model.document_packet_data import DocumentPacketData


class TestDocumentPacketData(unittest.TestCase):
    """DocumentPacketData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentPacketData(self):
        """Test DocumentPacketData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentPacketData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
