"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.phone_fields import PhoneFields
globals()['PhoneFields'] = PhoneFields
from elavon.model.address_fields import AddressFields


class TestAddressFields(unittest.TestCase):
    """AddressFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressFields(self):
        """Test AddressFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddressFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
