"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.ach_check_questions import AchCheckQuestions


class TestAchCheckQuestions(unittest.TestCase):
    """AchCheckQuestions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAchCheckQuestions(self):
        """Test AchCheckQuestions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AchCheckQuestions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
