"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.equipment_info import EquipmentInfo
globals()['EquipmentInfo'] = EquipmentInfo
from elavon.model.converge_terms_and_conditions_addendum_document_input import ConvergeTermsAndConditionsAddendumDocumentInput


class TestConvergeTermsAndConditionsAddendumDocumentInput(unittest.TestCase):
    """ConvergeTermsAndConditionsAddendumDocumentInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConvergeTermsAndConditionsAddendumDocumentInput(self):
        """Test ConvergeTermsAndConditionsAddendumDocumentInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConvergeTermsAndConditionsAddendumDocumentInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
