"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.phone_fields import PhoneFields


class TestPhoneFields(unittest.TestCase):
    """PhoneFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhoneFields(self):
        """Test PhoneFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PhoneFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
