"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.company_lightweight import CompanyLightweight
from elavon.model.timings import Timings
globals()['CompanyLightweight'] = CompanyLightweight
globals()['Timings'] = Timings
from elavon.model.company_query_response import CompanyQueryResponse


class TestCompanyQueryResponse(unittest.TestCase):
    """CompanyQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyQueryResponse(self):
        """Test CompanyQueryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompanyQueryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
