"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.http_session_context import HttpSessionContext
from elavon.model.servlet_context import ServletContext
globals()['HttpSessionContext'] = HttpSessionContext
globals()['ServletContext'] = ServletContext
from elavon.model.http_session import HttpSession


class TestHttpSession(unittest.TestCase):
    """HttpSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttpSession(self):
        """Test HttpSession"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HttpSession()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
