"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.delete_group_document_packet_response import DeleteGroupDocumentPacketResponse


class TestDeleteGroupDocumentPacketResponse(unittest.TestCase):
    """DeleteGroupDocumentPacketResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteGroupDocumentPacketResponse(self):
        """Test DeleteGroupDocumentPacketResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteGroupDocumentPacketResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
