"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.field_auto_info import FieldAutoInfo
from elavon.model.sales_rep_info import SalesRepInfo
globals()['FieldAutoInfo'] = FieldAutoInfo
globals()['SalesRepInfo'] = SalesRepInfo
from elavon.model.internal_use_info import InternalUseInfo


class TestInternalUseInfo(unittest.TestCase):
    """InternalUseInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInternalUseInfo(self):
        """Test InternalUseInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InternalUseInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
