"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.health_care_eligibility_info import HealthCareEligibilityInfo
from elavon.model.payments import Payments
globals()['HealthCareEligibilityInfo'] = HealthCareEligibilityInfo
globals()['Payments'] = Payments
from elavon.model.integrator_solution_info import IntegratorSolutionInfo


class TestIntegratorSolutionInfo(unittest.TestCase):
    """IntegratorSolutionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegratorSolutionInfo(self):
        """Test IntegratorSolutionInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegratorSolutionInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
