"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.enrollment_info import EnrollmentInfo
from elavon.model.loyalty_info import LoyaltyInfo
globals()['EnrollmentInfo'] = EnrollmentInfo
globals()['LoyaltyInfo'] = LoyaltyInfo
from elavon.model.fanfare_info import FanfareInfo


class TestFanfareInfo(unittest.TestCase):
    """FanfareInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFanfareInfo(self):
        """Test FanfareInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FanfareInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
