"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.check_document_signing_status_request import CheckDocumentSigningStatusRequest


class TestCheckDocumentSigningStatusRequest(unittest.TestCase):
    """CheckDocumentSigningStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckDocumentSigningStatusRequest(self):
        """Test CheckDocumentSigningStatusRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CheckDocumentSigningStatusRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
