"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.company_contact_info import CompanyContactInfo
from elavon.model.company_identification import CompanyIdentification
from elavon.model.company_merchant_detail import CompanyMerchantDetail
from elavon.model.company_principal import CompanyPrincipal
from elavon.model.company_summary import CompanySummary
from elavon.model.company_verification import CompanyVerification
from elavon.model.share_capital_structure import ShareCapitalStructure
from elavon.model.signer_info import SignerInfo
globals()['CompanyContactInfo'] = CompanyContactInfo
globals()['CompanyIdentification'] = CompanyIdentification
globals()['CompanyMerchantDetail'] = CompanyMerchantDetail
globals()['CompanyPrincipal'] = CompanyPrincipal
globals()['CompanySummary'] = CompanySummary
globals()['CompanyVerification'] = CompanyVerification
globals()['ShareCapitalStructure'] = ShareCapitalStructure
globals()['SignerInfo'] = SignerInfo
from elavon.model.company_info_bundle import CompanyInfoBundle


class TestCompanyInfoBundle(unittest.TestCase):
    """CompanyInfoBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyInfoBundle(self):
        """Test CompanyInfoBundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompanyInfoBundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
