"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.address import Address
from elavon.model.person import Person
globals()['Address'] = Address
globals()['Person'] = Person
from elavon.model.get_quiz_request import GetQuizRequest


class TestGetQuizRequest(unittest.TestCase):
    """GetQuizRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetQuizRequest(self):
        """Test GetQuizRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetQuizRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
