"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.ach_check_questions import AchCheckQuestions
globals()['AchCheckQuestions'] = AchCheckQuestions
from elavon.model.electronic_check_service import ElectronicCheckService


class TestElectronicCheckService(unittest.TestCase):
    """ElectronicCheckService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElectronicCheckService(self):
        """Test ElectronicCheckService"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ElectronicCheckService()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
