"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elavon
from elavon.model.module import Module
from elavon.model.package import Package
globals()['Module'] = Module
globals()['Package'] = Package
from elavon.model.class_loader import ClassLoader


class TestClassLoader(unittest.TestCase):
    """ClassLoader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClassLoader(self):
        """Test ClassLoader"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClassLoader()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
