"""
    Swagger Scarecrow

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from elavon.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from elavon.exceptions import ApiAttributeError



class GetUnsignedDocumentRequest(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('code',): {
            'OPERATING_GUIDE': "OPERATING_GUIDE",
            'TERMS_OF_SERVICE': "TERMS_OF_SERVICE",
            'PAY_NAV_MEDICAL_AND_BUSINESS_AGREEMENT': "PAY_NAV_MEDICAL_AND_BUSINESS_AGREEMENT",
            'TALECH_ADDENDUM': "TALECH_ADDENDUM",
            'TALECH_ELAVON_TERMS_AND_CONDITION_ADDENDUM': "TALECH_ELAVON_TERMS_AND_CONDITION_ADDENDUM",
            'TALECH_TERMS_OF_SERVICE': "TALECH_TERMS_OF_SERVICE",
            'AMEX_AGREEMENT': "AMEX_AGREEMENT",
            'AMEX_TERMS_OF_SERVICE': "AMEX_TERMS_OF_SERVICE",
            'SAFE_T_ADDENDUM': "SAFE_T_ADDENDUM",
            'BLIK_ADDENDUM': "BLIK_ADDENDUM",
            'EPG_TOC': "EPG_TOC",
            'APPLICATION': "APPLICATION",
            'MERCHANT_AGREEMENT': "MERCHANT_AGREEMENT",
            'SIGNED_APPLICATION': "SIGNED_APPLICATION",
            'UNSIGNED_APPLICATION': "UNSIGNED_APPLICATION",
            'DEPOSIT_DIRECT_DEBIT': "DEPOSIT_DIRECT_DEBIT",
            'DEPOSIT_SIGNED_DIRECT_DEBIT': "DEPOSIT_SIGNED_DIRECT_DEBIT",
            'BILLING_DIRECT_DEBIT': "BILLING_DIRECT_DEBIT",
            'BILLING_SIGNED_DIRECT_DEBIT': "BILLING_SIGNED_DIRECT_DEBIT",
            'CHARGEBACK_DIRECT_DEBIT': "CHARGEBACK_DIRECT_DEBIT",
            'CHARGEBACK_SIGNED_DIRECT_DEBIT': "CHARGEBACK_SIGNED_DIRECT_DEBIT",
            'APPLICATION_ADDENDUM': "APPLICATION_ADDENDUM",
            'TERMINAL_HIRE_AGREEMENT': "TERMINAL_HIRE_AGREEMENT",
            'TERMINAL_HIRE_PRE_CONTRACT': "TERMINAL_HIRE_PRE_CONTRACT",
            'TERMINAL_HIRE_AGREEMENT_STATUTORY': "TERMINAL_HIRE_AGREEMENT_STATUTORY",
            'CUSTOM_NOTES': "CUSTOM_NOTES",
            'CALIFORNIA_LEASE': "CALIFORNIA_LEASE",
            'LEASE_AGREEMENT': "LEASE_AGREEMENT",
            'ELAVON_SECURED_PRO_TOC': "ELAVON_SECURED_PRO_TOC",
            'ELAVON_SECURED_ENCRYPT_TOC': "ELAVON_SECURED_ENCRYPT_TOC",
            'EPG_ADDENDUM': "EPG_ADDENDUM",
            'PROMOTION_ADDENDUM': "PROMOTION_ADDENDUM",
            'CANADIAN_CODE_OF_CONDUCT': "CANADIAN_CODE_OF_CONDUCT",
            'ELAVON_TOKENIZATION_TOC': "ELAVON_TOKENIZATION_TOC",
            'GOVERNMENT_INCENTIVE_ADDENDUM': "GOVERNMENT_INCENTIVE_ADDENDUM",
            'AMEX_SITE_LETTER': "AMEX_SITE_LETTER",
            'SELF_GUARANTEE': "SELF_GUARANTEE",
            'POYNT_ADDENDUM': "POYNT_ADDENDUM",
            'CONVERGE_ADDENDUM': "CONVERGE_ADDENDUM",
            'SANTANDER_POS_ADDENDUM': "SANTANDER_POS_ADDENDUM",
            'CONVERGE_ELAVON_TERMS_AND_CONDITION_ADDENDUM': "CONVERGE_ELAVON_TERMS_AND_CONDITION_ADDENDUM",
            'KKT_ADDENDUM': "KKT_ADDENDUM",
            'OPAYO_TOS': "OPAYO_TOS",
            'PARTNER_DOCUMENTS': "PARTNER_DOCUMENTS",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'document_packet_id': (str,),  # noqa: E501
            'html': (bool,),  # noqa: E501
            'code': (str,),  # noqa: E501
            'cardinal_number': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'document_packet_id': 'documentPacketId',  # noqa: E501
        'html': 'html',  # noqa: E501
        'code': 'code',  # noqa: E501
        'cardinal_number': 'cardinalNumber',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """GetUnsignedDocumentRequest - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            document_packet_id (str): The unique identifier for the document packet. [optional]  # noqa: E501
            html (bool): If true, the document will be returned as HTML, if false the response will be PDF as a binary stream. [optional]  # noqa: E501
            code (str): The code related to which unsigned document is desired. [optional]  # noqa: E501
            cardinal_number (int): For PARTNER_DOCUMENTS. The cardinal related to which partner document is desired. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """GetUnsignedDocumentRequest - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            document_packet_id (str): The unique identifier for the document packet. [optional]  # noqa: E501
            html (bool): If true, the document will be returned as HTML, if false the response will be PDF as a binary stream. [optional]  # noqa: E501
            code (str): The code related to which unsigned document is desired. [optional]  # noqa: E501
            cardinal_number (int): For PARTNER_DOCUMENTS. The cardinal related to which partner document is desired. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
