# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AdditionalCardsTypeEnum(object):

    """Implementation of the 'AdditionalCardsType' enum.

    TODO: type enum description here.

    Attributes:
        FF_STANDARD: TODO: type description here.
        FF_CUSTOM: TODO: type description here.

    """

    FF_STANDARD = 'FF_STANDARD'

    FF_CUSTOM = 'FF_CUSTOM'
