# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from swaggerscarecrow.api_helper import APIHelper
from swaggerscarecrow.models.fraud_check_result import FraudCheckResult


class AnswerQuizResponse(object):

    """Implementation of the 'AnswerQuizResponse' model.

    TODO: type model description here.

    Attributes:
        response_id (int): TODO: type description here.
        fraud_check_result (FraudCheckResult): TODO: type description here.
        error (string): Error text should issue occur durring answer quiz
            operation

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "response_id": 'responseId',
        "fraud_check_result": 'fraudCheckResult',
        "error": 'error'
    }

    _optionals = [
        'response_id',
        'fraud_check_result',
        'error',
    ]

    def __init__(self,
                 response_id=APIHelper.SKIP,
                 fraud_check_result=APIHelper.SKIP,
                 error=APIHelper.SKIP):
        """Constructor for the AnswerQuizResponse class"""

        # Initialize members of the class
        if response_id is not APIHelper.SKIP:
            self.response_id = response_id 
        if fraud_check_result is not APIHelper.SKIP:
            self.fraud_check_result = fraud_check_result 
        if error is not APIHelper.SKIP:
            self.error = error 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        response_id = dictionary.get("responseId") if dictionary.get("responseId") else APIHelper.SKIP
        fraud_check_result = FraudCheckResult.from_dictionary(dictionary.get('fraudCheckResult')) if 'fraudCheckResult' in dictionary.keys() else APIHelper.SKIP 
        error = dictionary.get("error") if dictionary.get("error") else APIHelper.SKIP
        # Return an object of this model
        return cls(response_id,
                   fraud_check_result,
                   error)
