# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CategoryEnum(object):

    """Implementation of the 'Category' enum.

    Document Category

    Attributes:
        AML_OTHER: TODO: type description here.
        AML_OWNERSHIP_STRUCTURE: TODO: type description here.
        AML_PRINCIPAL_INFORMATION: TODO: type description here.
        BANK_DETAILS: TODO: type description here.
        BOARDING: TODO: type description here.
        CHARGEBACKS: TODO: type description here.
        CLOSURES: TODO: type description here.
        COMPLAINTS: TODO: type description here.
        CREDIT_AML_CHECKS: TODO: type description here.
        DEMOGRAPHIC_CHANGES: TODO: type description here.
        FRAUD: TODO: type description here.
        LEGAL_ENTITY_FORM: TODO: type description here.
        LIQUIDATION_BANKRUPTCY_DOCUMENTATION: TODO: type description here.
        LITIGATION_DOCUMENTATION: TODO: type description here.
        OTHER: TODO: type description here.
        PEP_AML_SANCTIONS: TODO: type description here.
        POS_CONTRACT_HIRE_AGREEMENT: TODO: type description here.
        PRICING: TODO: type description here.
        PRODUCT: TODO: type description here.
        RETURNED_MAIL: TODO: type description here.
        TERMINAL: TODO: type description here.
        TRANSACTION_REPROCESSING: TODO: type description here.
        VOUCHERS: TODO: type description here.

    """

    AML_OTHER = 'AML_OTHER'

    AML_OWNERSHIP_STRUCTURE = 'AML_OWNERSHIP_STRUCTURE'

    AML_PRINCIPAL_INFORMATION = 'AML_PRINCIPAL_INFORMATION'

    BANK_DETAILS = 'BANK_DETAILS'

    BOARDING = 'BOARDING'

    CHARGEBACKS = 'CHARGEBACKS'

    CLOSURES = 'CLOSURES'

    COMPLAINTS = 'COMPLAINTS'

    CREDIT_AML_CHECKS = 'CREDIT_AML_CHECKS'

    DEMOGRAPHIC_CHANGES = 'DEMOGRAPHIC_CHANGES'

    FRAUD = 'FRAUD'

    LEGAL_ENTITY_FORM = 'LEGAL_ENTITY_FORM'

    LIQUIDATION_BANKRUPTCY_DOCUMENTATION = 'LIQUIDATION_BANKRUPTCY_DOCUMENTATION'

    LITIGATION_DOCUMENTATION = 'LITIGATION_DOCUMENTATION'

    OTHER = 'OTHER'

    PEP_AML_SANCTIONS = 'PEP_AML_SANCTIONS'

    POS_CONTRACT_HIRE_AGREEMENT = 'POS_CONTRACT_HIRE_AGREEMENT'

    PRICING = 'PRICING'

    PRODUCT = 'PRODUCT'

    RETURNED_MAIL = 'RETURNED_MAIL'

    TERMINAL = 'TERMINAL'

    TRANSACTION_REPROCESSING = 'TRANSACTION_REPROCESSING'

    VOUCHERS = 'VOUCHERS'
