# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DecisionEnum(object):

    """Implementation of the 'Decision' enum.

    Result reached by quiz process

    Attributes:
        PASS: TODO: type description here.
        FAIL: TODO: type description here.
        NOT_APPLICABLE: TODO: type description here.

    """

    PASS = 'PASS'

    FAIL = 'FAIL'

    NOT_APPLICABLE = 'NOT_APPLICABLE'
