# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DispatcherTypeEnum(object):

    """Implementation of the 'DispatcherType' enum.

    TODO: type enum description here.

    Attributes:
        FORWARD: TODO: type description here.
        INCLUDE: TODO: type description here.
        REQUEST: TODO: type description here.
        ASYNC: TODO: type description here.
        ERROR: TODO: type description here.

    """

    FORWARD = 'FORWARD'

    INCLUDE = 'INCLUDE'

    REQUEST = 'REQUEST'

    ASYNC = 'ASYNC'

    ERROR = 'ERROR'
