# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DocumentaryTypeEnum(object):

    """Implementation of the 'DocumentaryType' enum.

    Type of documentation provided

    Attributes:
        DRIVER_LICENSE: TODO: type description here.
        FOREIGN_VISA: TODO: type description here.
        MATRICULA_CONSULAR: TODO: type description here.
        FOREIGEN_PHOTO_ID: TODO: type description here.
        US_ALIEN_ID: TODO: type description here.
        US_MILITARY_ID: TODO: type description here.
        STATE_ID: TODO: type description here.
        PASSPORT: TODO: type description here.
        TRIBAL_ID: TODO: type description here.
        CAN_US_DRIVER_LICENSE: TODO: type description here.
        CAN_US_GOVERNMENT_ISSUED_MILITARY_SERVICE_ID: TODO: type description
            here.
        CAN_US_STATE_ID: TODO: type description here.

    """

    DRIVER_LICENSE = 'DRIVER_LICENSE'

    FOREIGN_VISA = 'FOREIGN_VISA'

    MATRICULA_CONSULAR = 'MATRICULA_CONSULAR'

    FOREIGEN_PHOTO_ID = 'FOREIGEN_PHOTO_ID'

    US_ALIEN_ID = 'US_ALIEN_ID'

    US_MILITARY_ID = 'US_MILITARY_ID'

    STATE_ID = 'STATE_ID'

    PASSPORT = 'PASSPORT'

    TRIBAL_ID = 'TRIBAL_ID'

    CAN_US_DRIVER_LICENSE = 'CAN_US_DRIVER_LICENSE'

    CAN_US_GOVERNMENT_ISSUED_MILITARY_SERVICE_ID = 'CAN_US_GOVERNMENT_ISSUED_MILITARY_SERVICE_ID'

    CAN_US_STATE_ID = 'CAN_US_STATE_ID'
