# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EframeStatusEnum(object):

    """Implementation of the 'EframeStatus' enum.

    [EU][Elavon Germany] Eframe boarding Status

    Attributes:
        SUCCESS: TODO: type description here.
        ERROR: TODO: type description here.

    """

    SUCCESS = 'SUCCESS'

    ERROR = 'ERROR'
