# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from swaggerscarecrow.api_helper import APIHelper


class ExecuteGroupDocumentPacketResponse(object):

    """Implementation of the 'ExecuteGroupDocumentPacketResponse' model.

    TODO: type model description here.

    Attributes:
        response_id (int): TODO: type description here.
        error (string): Error message from service
        successful_execution (bool): Boolean flag indicating , true if
            execution successful, false if not

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "response_id": 'responseId',
        "error": 'error',
        "successful_execution": 'successfulExecution'
    }

    _optionals = [
        'response_id',
        'error',
        'successful_execution',
    ]

    def __init__(self,
                 response_id=APIHelper.SKIP,
                 error=APIHelper.SKIP,
                 successful_execution=APIHelper.SKIP):
        """Constructor for the ExecuteGroupDocumentPacketResponse class"""

        # Initialize members of the class
        if response_id is not APIHelper.SKIP:
            self.response_id = response_id 
        if error is not APIHelper.SKIP:
            self.error = error 
        if successful_execution is not APIHelper.SKIP:
            self.successful_execution = successful_execution 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        response_id = dictionary.get("responseId") if dictionary.get("responseId") else APIHelper.SKIP
        error = dictionary.get("error") if dictionary.get("error") else APIHelper.SKIP
        successful_execution = dictionary.get("successfulExecution") if "successfulExecution" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(response_id,
                   error,
                   successful_execution)
