# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Frequency1Enum(object):

    """Implementation of the 'Frequency1' enum.

    [EU] Frequency at which statement is provided

    Attributes:
        DAILY: TODO: type description here.
        WEEKLY: TODO: type description here.
        MONTHLY: TODO: type description here.

    """

    DAILY = 'DAILY'

    WEEKLY = 'WEEKLY'

    MONTHLY = 'MONTHLY'
