# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from swaggerscarecrow.api_helper import APIHelper
from swaggerscarecrow.models.user_document_input import UserDocumentInput


class GetDocumentsRequest(object):

    """Implementation of the 'GetDocumentsRequest' model.

    TODO: type model description here.

    Attributes:
        profile_code (string): The partner's profile code
        document_inputs (dict): The valid key-value pairs are as follows:
            OPERATING_GUIDE:MerchantOperatingGuideDocumentInput,
            TERMS_OF_SERVICE:TermsOfServiceDocumentInput,
            PAY_NAV_MEDICAL_AND_BUSINESS_AGREEMENT:UserDocumentInput,
            TALECH_ADDENDUM:TalechAddendumDocumentInput,
            TALECH_ELAVON_TERMS_AND_CONDITION_ADDENDUM:UserDocumentInput,
            TALECH_TERMS_OF_SERVICE:UserDocumentInput,
            AMEX_AGREEMENT:AmexDocumentInput,
            AMEX_TERMS_OF_SERVICE:UserDocumentInput,
            SAFE_T_ADDENDUM:UserDocumentInput,
            BLIK_ADDENDUM:BlikAddendumDocumentInput,
            EPG_TOC:UserDocumentInput,
            APPLICATION:MerchantAgreementDocumentInput,
            MERCHANT_AGREEMENT:MerchantAgreementDocumentInput,
            SIGNED_APPLICATION:MerchantAgreementDocumentInput,
            UNSIGNED_APPLICATION:MerchantAgreementDocumentInput,
            DEPOSIT_DIRECT_DEBIT:DirectDebitDocumentInput,
            DEPOSIT_SIGNED_DIRECT_DEBIT:DirectDebitDocumentInput,
            BILLING_DIRECT_DEBIT:DirectDebitDocumentInput,
            BILLING_SIGNED_DIRECT_DEBIT:DirectDebitDocumentInput,
            CHARGEBACK_DIRECT_DEBIT:DirectDebitDocumentInput,
            CHARGEBACK_SIGNED_DIRECT_DEBIT:DirectDebitDocumentInput,
            APPLICATION_ADDENDUM:MerchantAgreementDocumentInput,
            TERMINAL_HIRE_AGREEMENT:TerminalHireDocumentInput,
            TERMINAL_HIRE_PRE_CONTRACT:TerminalHireDocumentInput,
            TERMINAL_HIRE_AGREEMENT_STATUTORY:TerminalHireDocumentInput,
            CUSTOM_NOTES:CustomNotesDocumentInput,
            CALIFORNIA_LEASE:LeaseAgreementDocumentInput,
            LEASE_AGREEMENT:LeaseAgreementDocumentInput,
            ELAVON_SECURED_PRO_TOC:ElavonPciServiceDocumentInput,
            ELAVON_SECURED_ENCRYPT_TOC:ElavonPciServiceDocumentInput,
            EPG_ADDENDUM:ElavonPaymentGatewayAddendumDocumentInput,
            PROMOTION_ADDENDUM:PolishPromotionAddendumDocumentInput,
            CANADIAN_CODE_OF_CONDUCT:CanadianCodeOfConductDocumentInput,
            ELAVON_TOKENIZATION_TOC:ElavonTokenizationTermsAndConditionsDocumen
            tInput,
            GOVERNMENT_INCENTIVE_ADDENDUM:GovernmentIncentiveAddendumDocumentIn
            put, AMEX_SITE_LETTER:AmexDocumentInput,
            SELF_GUARANTEE:PersonalGuaranteeDocumentInput,
            POYNT_ADDENDUM:PoyntAddendumDocumentInput,
            CONVERGE_ADDENDUM:ConvergeAddendumDocumentInput,
            SANTANDER_POS_ADDENDUM:SantanderPosAddendumDocumentInput,
            CONVERGE_ELAVON_TERMS_AND_CONDITION_ADDENDUM:ConvergeTermsAndCondit
            ionsAddendumDocumentInput, KKT_ADDENDUM:KktAddendumDocumentInput,
            OPAYO_TOS:UserDocumentInput,
            PARTNER_DOCUMENTS:PartnerDocumentInput
        html (bool): Boolean indicating if return should be encoded as a PDF
            or HTML. Boolean true for HTML, false for PDF

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "profile_code": 'profileCode',
        "document_inputs": 'documentInputs',
        "html": 'html'
    }

    _optionals = [
        'profile_code',
        'document_inputs',
        'html',
    ]

    def __init__(self,
                 profile_code=APIHelper.SKIP,
                 document_inputs=APIHelper.SKIP,
                 html=APIHelper.SKIP):
        """Constructor for the GetDocumentsRequest class"""

        # Initialize members of the class
        if profile_code is not APIHelper.SKIP:
            self.profile_code = profile_code 
        if document_inputs is not APIHelper.SKIP:
            self.document_inputs = document_inputs 
        if html is not APIHelper.SKIP:
            self.html = html 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        profile_code = dictionary.get("profileCode") if dictionary.get("profileCode") else APIHelper.SKIP
        document_inputs = UserDocumentInput.from_dictionary(dictionary.get('documentInputs')) if 'documentInputs' in dictionary.keys() else APIHelper.SKIP 
        html = dictionary.get("html") if "html" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(profile_code,
                   document_inputs,
                   html)
