# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IncompleteSurveyReasonTypeEnum(object):

    """Implementation of the 'IncompleteSurveyReasonType' enum.

    TODO: type enum description here.

    Attributes:
        NOT_OPEN: TODO: type description here.
        REMOTE_SIGN: TODO: type description here.
        ECOM_CUSTOMER: TODO: type description here.
        OTHER: TODO: type description here.

    """

    NOT_OPEN = 'NOT_OPEN'

    REMOTE_SIGN = 'REMOTE_SIGN'

    ECOM_CUSTOMER = 'ECOM_CUSTOMER'

    OTHER = 'OTHER'
