# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IndustryClassEnum(object):

    """Implementation of the 'IndustryClass' enum.

    [NA] Business industry classification

    Attributes:
        LODGING: TODO: type description here.
        MOTO: TODO: type description here.
        RESTAURANT: TODO: type description here.
        RETAIL: TODO: type description here.
        INTERNET: TODO: type description here.

    """

    LODGING = 'LODGING'

    MOTO = 'MOTO'

    RESTAURANT = 'RESTAURANT'

    RETAIL = 'RETAIL'

    INTERNET = 'INTERNET'
