# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LocationEnvironmentEnum(object):

    """Implementation of the 'LocationEnvironment' enum.

    [EU] The type of site location

    Attributes:
        BUSINESS_DISTRICT: TODO: type description here.
        INDUSTRIAL_ESTATE: TODO: type description here.
        RESIDENTIAL: TODO: type description here.
        RETAIL: TODO: type description here.

    """

    BUSINESS_DISTRICT = 'BUSINESS_DISTRICT'

    INDUSTRIAL_ESTATE = 'INDUSTRIAL_ESTATE'

    RESIDENTIAL = 'RESIDENTIAL'

    RETAIL = 'RETAIL'
