# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MethodEnum(object):

    """Implementation of the 'Method' enum.

    Method of distribution

    Attributes:
        MAILING: TODO: type description here.
        FAX: TODO: type description here.
        MAILING_AND_FAX: TODO: type description here.
        EMAIL: TODO: type description here.
        BUSINESS: TODO: type description here.
        CHARGEBACK: TODO: type description here.
        SHIPPING: TODO: type description here.
        ELECTRONIC: TODO: type description here.
        NONE: TODO: type description here.
        BRANCH_FAX: TODO: type description here.
        MAIL: TODO: type description here.
        OCM: TODO: type description here.

    """

    MAILING = 'MAILING'

    FAX = 'FAX'

    MAILING_AND_FAX = 'MAILING_AND_FAX'

    EMAIL = 'EMAIL'

    BUSINESS = 'BUSINESS'

    CHARGEBACK = 'CHARGEBACK'

    SHIPPING = 'SHIPPING'

    ELECTRONIC = 'ELECTRONIC'

    NONE = 'NONE'

    BRANCH_FAX = 'BRANCH_FAX'

    MAIL = 'MAIL'

    OCM = 'OCM'
