# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MimeTypeCodeEnum(object):

    """Implementation of the 'MimeTypeCode' enum.

    MIME type

    Attributes:
        JPG: TODO: type description here.
        PDF: TODO: type description here.
        SVG: TODO: type description here.
        DOC: TODO: type description here.
        XLS: TODO: type description here.
        TIFF: TODO: type description here.
        BMP: TODO: type description here.
        TIF: TODO: type description here.
        JPEG: TODO: type description here.
        RTF: TODO: type description here.
        DOCX: TODO: type description here.
        XLSX: TODO: type description here.
        PPT: TODO: type description here.
        PPTX: TODO: type description here.
        VSD: TODO: type description here.
        VDX: TODO: type description here.
        VSDX: TODO: type description here.
        HTM: TODO: type description here.
        HTML: TODO: type description here.
        PNG: TODO: type description here.
        MSG: TODO: type description here.
        XPS: TODO: type description here.

    """

    JPG = 'JPG'

    PDF = 'PDF'

    SVG = 'SVG'

    DOC = 'DOC'

    XLS = 'XLS'

    TIFF = 'TIFF'

    BMP = 'BMP'

    TIF = 'TIF'

    JPEG = 'JPEG'

    RTF = 'RTF'

    DOCX = 'DOCX'

    XLSX = 'XLSX'

    PPT = 'PPT'

    PPTX = 'PPTX'

    VSD = 'VSD'

    VDX = 'VDX'

    VSDX = 'VSDX'

    HTM = 'HTM'

    HTML = 'HTML'

    PNG = 'PNG'

    MSG = 'MSG'

    XPS = 'XPS'
