# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NumberOptionEnum(object):

    """Implementation of the 'NumberOption' enum.

    Type of VAT id provieded if tax id type is VAT

    Attributes:
        VAT_NBR: TODO: type description here.
        VAT_NBR_PEND: TODO: type description here.
        IN_BUSNS_CONF: TODO: type description here.

    """

    VAT_NBR = 'VAT_NBR'

    VAT_NBR_PEND = 'VAT_NBR_PEND'

    IN_BUSNS_CONF = 'IN_BUSNS_CONF'
