# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PricingTier(object):

    """Implementation of the 'PricingTier' model.

    The pricing tier describes any discount rates or discounts per item that
    should apply to the card product

    Attributes:
        discount_rate (float): Card discount rate/fee percentage
        discount_per_item (float): Card discount per item/per transaction fee

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "discount_rate": 'discountRate',
        "discount_per_item": 'discountPerItem'
    }

    def __init__(self,
                 discount_rate=None,
                 discount_per_item=None):
        """Constructor for the PricingTier class"""

        # Initialize members of the class
        self.discount_rate = discount_rate 
        self.discount_per_item = discount_per_item 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        discount_rate = dictionary.get("discountRate") if dictionary.get("discountRate") else None
        discount_per_item = dictionary.get("discountPerItem") if dictionary.get("discountPerItem") else None
        # Return an object of this model
        return cls(discount_rate,
                   discount_per_item)
