# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProcessErrorTypeEnum(object):

    """Implementation of the 'ProcessErrorType' enum.

    TODO: type enum description here.

    Attributes:
        BOARDING: TODO: type description here.
        DOCUMENT_PACKET: TODO: type description here.

    """

    BOARDING = 'BOARDING'

    DOCUMENT_PACKET = 'DOCUMENT_PACKET'
