# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProcessingAcceptanceTypeEnum(object):

    """Implementation of the 'ProcessingAcceptanceType' enum.

    ECS processing acceptance

    Attributes:
        POP_POS_IMAGE: TODO: type description here.
        BOC_POS_IMAGE: TODO: type description here.
        BOC_CASH_OFFICE_IMAGE: TODO: type description here.
        ARC: TODO: type description here.
        ACH_CONCURRENT: TODO: type description here.

    """

    POP_POS_IMAGE = 'POP_POS_IMAGE'

    BOC_POS_IMAGE = 'BOC_POS_IMAGE'

    BOC_CASH_OFFICE_IMAGE = 'BOC_CASH_OFFICE_IMAGE'

    ARC = 'ARC'

    ACH_CONCURRENT = 'ACH_CONCURRENT'
