# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RegenerateDocumentPacketRequest(object):

    """Implementation of the 'RegenerateDocumentPacketRequest' model.

    TODO: type model description here.

    Attributes:
        document_packet_id (string): The unique id for the document packet

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "document_packet_id": 'documentPacketId'
    }

    def __init__(self,
                 document_packet_id=None):
        """Constructor for the RegenerateDocumentPacketRequest class"""

        # Initialize members of the class
        self.document_packet_id = document_packet_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        document_packet_id = dictionary.get("documentPacketId") if dictionary.get("documentPacketId") else None
        # Return an object of this model
        return cls(document_packet_id)
