# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SalutationEnum(object):

    """Implementation of the 'Salutation' enum.

    TODO: type enum description here.

    Attributes:
        MR: TODO: type description here.
        MRS: TODO: type description here.
        MS: TODO: type description here.
        MISS: TODO: type description here.
        JR: TODO: type description here.
        SR: TODO: type description here.
        DR: TODO: type description here.
        MASTER: TODO: type description here.
        PROF: TODO: type description here.

    """

    MR = 'MR'

    MRS = 'MRS'

    MS = 'MS'

    MISS = 'MISS'

    JR = 'JR'

    SR = 'SR'

    DR = 'DR'

    MASTER = 'MASTER'

    PROF = 'PROF'
