# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from swaggerscarecrow.api_helper import APIHelper


class ServletRegistration(object):

    """Implementation of the 'ServletRegistration' model.

    TODO: type model description here.

    Attributes:
        mappings (list of string): TODO: type description here.
        run_as_role (string): TODO: type description here.
        name (string): TODO: type description here.
        class_name (string): TODO: type description here.
        init_parameters (dict): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mappings": 'mappings',
        "run_as_role": 'runAsRole',
        "name": 'name',
        "class_name": 'className',
        "init_parameters": 'initParameters'
    }

    _optionals = [
        'mappings',
        'run_as_role',
        'name',
        'class_name',
        'init_parameters',
    ]

    def __init__(self,
                 mappings=APIHelper.SKIP,
                 run_as_role=APIHelper.SKIP,
                 name=APIHelper.SKIP,
                 class_name=APIHelper.SKIP,
                 init_parameters=APIHelper.SKIP):
        """Constructor for the ServletRegistration class"""

        # Initialize members of the class
        if mappings is not APIHelper.SKIP:
            self.mappings = mappings 
        if run_as_role is not APIHelper.SKIP:
            self.run_as_role = run_as_role 
        if name is not APIHelper.SKIP:
            self.name = name 
        if class_name is not APIHelper.SKIP:
            self.class_name = class_name 
        if init_parameters is not APIHelper.SKIP:
            self.init_parameters = init_parameters 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        mappings = dictionary.get("mappings") if dictionary.get("mappings") else APIHelper.SKIP
        run_as_role = dictionary.get("runAsRole") if dictionary.get("runAsRole") else APIHelper.SKIP
        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        class_name = dictionary.get("className") if dictionary.get("className") else APIHelper.SKIP
        init_parameters = dictionary.get("initParameters") if dictionary.get("initParameters") else APIHelper.SKIP
        # Return an object of this model
        return cls(mappings,
                   run_as_role,
                   name,
                   class_name,
                   init_parameters)
