# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SignedTypeEnum(object):

    """Implementation of the 'SignedType' enum.

    [NA] How application was signed

    Attributes:
        WET: TODO: type description here.
        ELECTRONIC: TODO: type description here.

    """

    WET = 'WET'

    ELECTRONIC = 'ELECTRONIC'
