# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SignerStatusEnum(object):

    """Implementation of the 'SignerStatus' enum.

    The signer's id and state

    Attributes:
        DRAFT: TODO: type description here.
        ACCEPTED: TODO: type description here.
        SIGNED: TODO: type description here.
        DECLINED: TODO: type description here.
        EXPIRED: TODO: type description here.

    """

    DRAFT = 'DRAFT'

    ACCEPTED = 'ACCEPTED'

    SIGNED = 'SIGNED'

    DECLINED = 'DECLINED'

    EXPIRED = 'EXPIRED'
