# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from swaggerscarecrow.api_helper import APIHelper


class TerminalService(object):

    """Implementation of the 'TerminalService' model.

    A container to hold any terminal services that should be applied to the
    equipment

    Attributes:
        mtype (Type6Enum): Type of terminal service to be provided
        service_specifics (string): [NA] Free text for additional
            specification of terminal service details

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": 'type',
        "service_specifics": 'serviceSpecifics'
    }

    _optionals = [
        'service_specifics',
    ]

    def __init__(self,
                 mtype=None,
                 service_specifics=APIHelper.SKIP):
        """Constructor for the TerminalService class"""

        # Initialize members of the class
        self.mtype = mtype 
        if service_specifics is not APIHelper.SKIP:
            self.service_specifics = service_specifics 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        mtype = dictionary.get("type") if dictionary.get("type") else None
        service_specifics = dictionary.get("serviceSpecifics") if dictionary.get("serviceSpecifics") else APIHelper.SKIP
        # Return an object of this model
        return cls(mtype,
                   service_specifics)
