# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TitleTypeEnum(object):

    """Implementation of the 'TitleType' enum.

    [NA] Title type of person

    Attributes:
        ACCOUNTING_MANAGER: TODO: type description here.
        AUTHORIZED_SIGNER: TODO: type description here.
        CONTROLLER: TODO: type description here.
        CHIEF_EXECUTIVE_OFFICER: TODO: type description here.
        CHIEF_FINANCIAL_OFFICER: TODO: type description here.
        CHIEF_OPERATING_OFFICER: TODO: type description here.
        CHAIRMAN: TODO: type description here.
        COSIGNER: TODO: type description here.
        DIRECTOR: TODO: type description here.
        GENERAL_MANAGER: TODO: type description here.
        GENERAL_PARTNER: TODO: type description here.
        GUARANTOR: TODO: type description here.
        MANAGING_MEMBER: TODO: type description here.
        OFFICER: TODO: type description here.
        PROPRIETOR_OR_OWNER: TODO: type description here.
        PRESIDENT: TODO: type description here.
        PARTNER_OR_PRINCIPAL: TODO: type description here.
        SECRETARY: TODO: type description here.
        TREASURER: TODO: type description here.
        TRUSTEE: TODO: type description here.
        VICE_PRESIDENT: TODO: type description here.
        OTHER: TODO: type description here.

    """

    ACCOUNTING_MANAGER = 'ACCOUNTING_MANAGER'

    AUTHORIZED_SIGNER = 'AUTHORIZED_SIGNER'

    CONTROLLER = 'CONTROLLER'

    CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER'

    CHIEF_FINANCIAL_OFFICER = 'CHIEF_FINANCIAL_OFFICER'

    CHIEF_OPERATING_OFFICER = 'CHIEF_OPERATING_OFFICER'

    CHAIRMAN = 'CHAIRMAN'

    COSIGNER = 'COSIGNER'

    DIRECTOR = 'DIRECTOR'

    GENERAL_MANAGER = 'GENERAL_MANAGER'

    GENERAL_PARTNER = 'GENERAL_PARTNER'

    GUARANTOR = 'GUARANTOR'

    MANAGING_MEMBER = 'MANAGING_MEMBER'

    OFFICER = 'OFFICER'

    PROPRIETOR_OR_OWNER = 'PROPRIETOR_OR_OWNER'

    PRESIDENT = 'PRESIDENT'

    PARTNER_OR_PRINCIPAL = 'PARTNER_OR_PRINCIPAL'

    SECRETARY = 'SECRETARY'

    TREASURER = 'TREASURER'

    TRUSTEE = 'TRUSTEE'

    VICE_PRESIDENT = 'VICE_PRESIDENT'

    OTHER = 'OTHER'
