# -*- coding: utf-8 -*-

"""
swaggerscarecrow

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class VicinityConditionEnum(object):

    """Implementation of the 'VicinityCondition' enum.

    [EU] The condition of the site's vicinity

    Attributes:
        WELL_KEPT: TODO: type description here.
        REGENERATION: TODO: type description here.
        DETERIORATION: TODO: type description here.

    """

    WELL_KEPT = 'WELL_KEPT'

    REGENERATION = 'REGENERATION'

    DETERIORATION = 'DETERIORATION'
