<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class AdditionalBusinessInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $ownershipYearsOverRange;

    /**
     * @var bool|null
     */
    private $isMaxEstablishmentYear;

    /**
     * @var bool|null
     */
    private $hasGovernmentIncentive;

    /**
     * Returns Ownership Years Over Range.
     * Years over max allowed ownership length
     */
    public function getOwnershipYearsOverRange(): ?string
    {
        return $this->ownershipYearsOverRange;
    }

    /**
     * Sets Ownership Years Over Range.
     * Years over max allowed ownership length
     *
     * @maps ownershipYearsOverRange
     */
    public function setOwnershipYearsOverRange(?string $ownershipYearsOverRange): void
    {
        $this->ownershipYearsOverRange = $ownershipYearsOverRange;
    }

    /**
     * Returns Is Max Establishment Year.
     * True if business establishment year is older than 1906
     */
    public function getIsMaxEstablishmentYear(): ?bool
    {
        return $this->isMaxEstablishmentYear;
    }

    /**
     * Sets Is Max Establishment Year.
     * True if business establishment year is older than 1906
     *
     * @maps isMaxEstablishmentYear
     */
    public function setIsMaxEstablishmentYear(?bool $isMaxEstablishmentYear): void
    {
        $this->isMaxEstablishmentYear = $isMaxEstablishmentYear;
    }

    /**
     * Returns Has Government Incentive.
     * True if business has a government incentive
     */
    public function getHasGovernmentIncentive(): ?bool
    {
        return $this->hasGovernmentIncentive;
    }

    /**
     * Sets Has Government Incentive.
     * True if business has a government incentive
     *
     * @maps hasGovernmentIncentive
     */
    public function setHasGovernmentIncentive(?bool $hasGovernmentIncentive): void
    {
        $this->hasGovernmentIncentive = $hasGovernmentIncentive;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ownershipYearsOverRange)) {
            $json['ownershipYearsOverRange'] = $this->ownershipYearsOverRange;
        }
        if (isset($this->isMaxEstablishmentYear)) {
            $json['isMaxEstablishmentYear']  = $this->isMaxEstablishmentYear;
        }
        if (isset($this->hasGovernmentIncentive)) {
            $json['hasGovernmentIncentive']  = $this->hasGovernmentIncentive;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
