<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class AdditionalLocationInfo implements \JsonSerializable
{
    /**
     * @var string
     */
    private $centralMid;

    /**
     * @var string
     */
    private $centralLegalName;

    /**
     * @var string|null
     */
    private $centralTaxId;

    /**
     * @param string $centralMid
     * @param string $centralLegalName
     */
    public function __construct(string $centralMid, string $centralLegalName)
    {
        $this->centralMid = $centralMid;
        $this->centralLegalName = $centralLegalName;
    }

    /**
     * Returns Central Mid.
     * Merchant Id of existing business
     */
    public function getCentralMid(): string
    {
        return $this->centralMid;
    }

    /**
     * Sets Central Mid.
     * Merchant Id of existing business
     *
     * @required
     * @maps centralMid
     */
    public function setCentralMid(string $centralMid): void
    {
        $this->centralMid = $centralMid;
    }

    /**
     * Returns Central Legal Name.
     * Legal Name of existing business
     */
    public function getCentralLegalName(): string
    {
        return $this->centralLegalName;
    }

    /**
     * Sets Central Legal Name.
     * Legal Name of existing business
     *
     * @required
     * @maps centralLegalName
     */
    public function setCentralLegalName(string $centralLegalName): void
    {
        $this->centralLegalName = $centralLegalName;
    }

    /**
     * Returns Central Tax Id.
     * Tax Id of existing busines, required in cases where Central Legal Name not present
     */
    public function getCentralTaxId(): ?string
    {
        return $this->centralTaxId;
    }

    /**
     * Sets Central Tax Id.
     * Tax Id of existing busines, required in cases where Central Legal Name not present
     *
     * @maps centralTaxId
     */
    public function setCentralTaxId(?string $centralTaxId): void
    {
        $this->centralTaxId = $centralTaxId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['centralMid']       = $this->centralMid;
        $json['centralLegalName'] = $this->centralLegalName;
        if (isset($this->centralTaxId)) {
            $json['centralTaxId'] = $this->centralTaxId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
