<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class AdditionalSiteSurveyInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $incompleteSurveyReasonType;

    /**
     * @var DateComponents|null
     */
    private $siteSurveyDate;

    /**
     * @var string|null
     */
    private $siteSurveyConductedBy;

    /**
     * @var string|null
     */
    private $descriptionOfNoSiteSurvey;

    /**
     * Returns Incomplete Survey Reason Type.
     */
    public function getIncompleteSurveyReasonType(): ?string
    {
        return $this->incompleteSurveyReasonType;
    }

    /**
     * Sets Incomplete Survey Reason Type.
     *
     * @maps incompleteSurveyReasonType
     * @factory \SwaggerScarecrowLib\Models\IncompleteSurveyReasonTypeEnum::checkValue
     */
    public function setIncompleteSurveyReasonType(?string $incompleteSurveyReasonType): void
    {
        $this->incompleteSurveyReasonType = $incompleteSurveyReasonType;
    }

    /**
     * Returns Site Survey Date.
     * A container that holds the date (day, month, and year)
     */
    public function getSiteSurveyDate(): ?DateComponents
    {
        return $this->siteSurveyDate;
    }

    /**
     * Sets Site Survey Date.
     * A container that holds the date (day, month, and year)
     *
     * @maps siteSurveyDate
     */
    public function setSiteSurveyDate(?DateComponents $siteSurveyDate): void
    {
        $this->siteSurveyDate = $siteSurveyDate;
    }

    /**
     * Returns Site Survey Conducted By.
     */
    public function getSiteSurveyConductedBy(): ?string
    {
        return $this->siteSurveyConductedBy;
    }

    /**
     * Sets Site Survey Conducted By.
     *
     * @maps siteSurveyConductedBy
     */
    public function setSiteSurveyConductedBy(?string $siteSurveyConductedBy): void
    {
        $this->siteSurveyConductedBy = $siteSurveyConductedBy;
    }

    /**
     * Returns Description of No Site Survey.
     */
    public function getDescriptionOfNoSiteSurvey(): ?string
    {
        return $this->descriptionOfNoSiteSurvey;
    }

    /**
     * Sets Description of No Site Survey.
     *
     * @maps descriptionOfNoSiteSurvey
     */
    public function setDescriptionOfNoSiteSurvey(?string $descriptionOfNoSiteSurvey): void
    {
        $this->descriptionOfNoSiteSurvey = $descriptionOfNoSiteSurvey;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->incompleteSurveyReasonType)) {
            $json['incompleteSurveyReasonType'] =
                IncompleteSurveyReasonTypeEnum::checkValue(
                    $this->incompleteSurveyReasonType
                );
        }
        if (isset($this->siteSurveyDate)) {
            $json['siteSurveyDate']             = $this->siteSurveyDate;
        }
        if (isset($this->siteSurveyConductedBy)) {
            $json['siteSurveyConductedBy']      = $this->siteSurveyConductedBy;
        }
        if (isset($this->descriptionOfNoSiteSurvey)) {
            $json['descriptionOfNoSiteSurvey']  = $this->descriptionOfNoSiteSurvey;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
