<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class AdditionalCardPricingInfo implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $minimumCardFee;

    /**
     * @var string|null
     */
    private $clearAndSimpleType;

    /**
     * @var string|null
     */
    private $c4PricingType;

    /**
     * @var string|null
     */
    private $highRiskCostAdditionalLoading;

    /**
     * Returns Minimum Card Fee.
     * Minimum charge fee to be applied to card
     */
    public function getMinimumCardFee(): ?float
    {
        return $this->minimumCardFee;
    }

    /**
     * Sets Minimum Card Fee.
     * Minimum charge fee to be applied to card
     *
     * @maps minimumCardFee
     */
    public function setMinimumCardFee(?float $minimumCardFee): void
    {
        $this->minimumCardFee = $minimumCardFee;
    }

    /**
     * Returns Clear and Simple Type.
     * The type of the clear and simple plan
     */
    public function getClearAndSimpleType(): ?string
    {
        return $this->clearAndSimpleType;
    }

    /**
     * Sets Clear and Simple Type.
     * The type of the clear and simple plan
     *
     * @maps clearAndSimpleType
     */
    public function setClearAndSimpleType(?string $clearAndSimpleType): void
    {
        $this->clearAndSimpleType = $clearAndSimpleType;
    }

    /**
     * Returns C 4 Pricing Type.
     * The type of the C4 pricing plan
     */
    public function getC4PricingType(): ?string
    {
        return $this->c4PricingType;
    }

    /**
     * Sets C 4 Pricing Type.
     * The type of the C4 pricing plan
     *
     * @maps c4PricingType
     */
    public function setC4PricingType(?string $c4PricingType): void
    {
        $this->c4PricingType = $c4PricingType;
    }

    /**
     * Returns High Risk Cost Additional Loading.
     * Risk loading percentage as it relates to Simplified MSC
     */
    public function getHighRiskCostAdditionalLoading(): ?string
    {
        return $this->highRiskCostAdditionalLoading;
    }

    /**
     * Sets High Risk Cost Additional Loading.
     * Risk loading percentage as it relates to Simplified MSC
     *
     * @maps highRiskCostAdditionalLoading
     */
    public function setHighRiskCostAdditionalLoading(?string $highRiskCostAdditionalLoading): void
    {
        $this->highRiskCostAdditionalLoading = $highRiskCostAdditionalLoading;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->minimumCardFee)) {
            $json['minimumCardFee']                = $this->minimumCardFee;
        }
        if (isset($this->clearAndSimpleType)) {
            $json['clearAndSimpleType']            = $this->clearAndSimpleType;
        }
        if (isset($this->c4PricingType)) {
            $json['c4PricingType']                 = $this->c4PricingType;
        }
        if (isset($this->highRiskCostAdditionalLoading)) {
            $json['highRiskCostAdditionalLoading'] = $this->highRiskCostAdditionalLoading;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
