<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class CompanyInfoBundle implements \JsonSerializable
{
    /**
     * @var SignerInfo|null
     */
    private $signerInfo;

    /**
     * @var CompanySummary|null
     */
    private $companySummary;

    /**
     * @var CompanyIdentification|null
     */
    private $companyIdentification;

    /**
     * @var CompanyContactInfo|null
     */
    private $companyContactInfo;

    /**
     * @var CompanyContactInfo[]|null
     */
    private $contactInformationOtherAddresses;

    /**
     * @var CompanyPrincipal[]|null
     */
    private $directorAndManagers;

    /**
     * @var ShareCapitalStructure|null
     */
    private $shareCapitalStructure;

    /**
     * @var CompanyVerification|null
     */
    private $companyVerification;

    /**
     * @var CompanyMerchantDetail|null
     */
    private $companyMerchantDetail;

    /**
     * Returns Signer Info.
     */
    public function getSignerInfo(): ?SignerInfo
    {
        return $this->signerInfo;
    }

    /**
     * Sets Signer Info.
     *
     * @maps signerInfo
     */
    public function setSignerInfo(?SignerInfo $signerInfo): void
    {
        $this->signerInfo = $signerInfo;
    }

    /**
     * Returns Company Summary.
     */
    public function getCompanySummary(): ?CompanySummary
    {
        return $this->companySummary;
    }

    /**
     * Sets Company Summary.
     *
     * @maps companySummary
     */
    public function setCompanySummary(?CompanySummary $companySummary): void
    {
        $this->companySummary = $companySummary;
    }

    /**
     * Returns Company Identification.
     */
    public function getCompanyIdentification(): ?CompanyIdentification
    {
        return $this->companyIdentification;
    }

    /**
     * Sets Company Identification.
     *
     * @maps companyIdentification
     */
    public function setCompanyIdentification(?CompanyIdentification $companyIdentification): void
    {
        $this->companyIdentification = $companyIdentification;
    }

    /**
     * Returns Company Contact Info.
     */
    public function getCompanyContactInfo(): ?CompanyContactInfo
    {
        return $this->companyContactInfo;
    }

    /**
     * Sets Company Contact Info.
     *
     * @maps companyContactInfo
     */
    public function setCompanyContactInfo(?CompanyContactInfo $companyContactInfo): void
    {
        $this->companyContactInfo = $companyContactInfo;
    }

    /**
     * Returns Contact Information Other Addresses.
     *
     * @return CompanyContactInfo[]|null
     */
    public function getContactInformationOtherAddresses(): ?array
    {
        return $this->contactInformationOtherAddresses;
    }

    /**
     * Sets Contact Information Other Addresses.
     *
     * @maps contactInformationOtherAddresses
     *
     * @param CompanyContactInfo[]|null $contactInformationOtherAddresses
     */
    public function setContactInformationOtherAddresses(?array $contactInformationOtherAddresses): void
    {
        $this->contactInformationOtherAddresses = $contactInformationOtherAddresses;
    }

    /**
     * Returns Director and Managers.
     *
     * @return CompanyPrincipal[]|null
     */
    public function getDirectorAndManagers(): ?array
    {
        return $this->directorAndManagers;
    }

    /**
     * Sets Director and Managers.
     *
     * @maps directorAndManagers
     *
     * @param CompanyPrincipal[]|null $directorAndManagers
     */
    public function setDirectorAndManagers(?array $directorAndManagers): void
    {
        $this->directorAndManagers = $directorAndManagers;
    }

    /**
     * Returns Share Capital Structure.
     */
    public function getShareCapitalStructure(): ?ShareCapitalStructure
    {
        return $this->shareCapitalStructure;
    }

    /**
     * Sets Share Capital Structure.
     *
     * @maps shareCapitalStructure
     */
    public function setShareCapitalStructure(?ShareCapitalStructure $shareCapitalStructure): void
    {
        $this->shareCapitalStructure = $shareCapitalStructure;
    }

    /**
     * Returns Company Verification.
     */
    public function getCompanyVerification(): ?CompanyVerification
    {
        return $this->companyVerification;
    }

    /**
     * Sets Company Verification.
     *
     * @maps companyVerification
     */
    public function setCompanyVerification(?CompanyVerification $companyVerification): void
    {
        $this->companyVerification = $companyVerification;
    }

    /**
     * Returns Company Merchant Detail.
     */
    public function getCompanyMerchantDetail(): ?CompanyMerchantDetail
    {
        return $this->companyMerchantDetail;
    }

    /**
     * Sets Company Merchant Detail.
     *
     * @maps companyMerchantDetail
     */
    public function setCompanyMerchantDetail(?CompanyMerchantDetail $companyMerchantDetail): void
    {
        $this->companyMerchantDetail = $companyMerchantDetail;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->signerInfo)) {
            $json['signerInfo']                       = $this->signerInfo;
        }
        if (isset($this->companySummary)) {
            $json['companySummary']                   = $this->companySummary;
        }
        if (isset($this->companyIdentification)) {
            $json['companyIdentification']            = $this->companyIdentification;
        }
        if (isset($this->companyContactInfo)) {
            $json['companyContactInfo']               = $this->companyContactInfo;
        }
        if (isset($this->contactInformationOtherAddresses)) {
            $json['contactInformationOtherAddresses'] = $this->contactInformationOtherAddresses;
        }
        if (isset($this->directorAndManagers)) {
            $json['directorAndManagers']              = $this->directorAndManagers;
        }
        if (isset($this->shareCapitalStructure)) {
            $json['shareCapitalStructure']            = $this->shareCapitalStructure;
        }
        if (isset($this->companyVerification)) {
            $json['companyVerification']              = $this->companyVerification;
        }
        if (isset($this->companyMerchantDetail)) {
            $json['companyMerchantDetail']            = $this->companyMerchantDetail;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
