<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;
use SwaggerScarecrowLib\Utils\DateTimeHelper;

class CompanyPrincipal implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $gender;

    /**
     * @var \DateTime|null
     */
    private $dateOfBirth;

    /**
     * @var AddressFields|null
     */
    private $address;

    /**
     * @var string[]|null
     */
    private $positions;

    /**
     * @var PersonNameFields|null
     */
    private $personNameFields;

    /**
     * @var PhoneFields|null
     */
    private $phoneFields;

    /**
     * @var PhoneFields|null
     */
    private $mobilePhoneFields;

    /**
     * @var string|null
     */
    private $principalIdentifier;

    /**
     * @var PrincipalOwnerDetail|null
     */
    private $principalOwnerDetail;

    /**
     * @var string|null
     */
    private $pesel;

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Gender.
     */
    public function getGender(): ?string
    {
        return $this->gender;
    }

    /**
     * Sets Gender.
     *
     * @maps gender
     */
    public function setGender(?string $gender): void
    {
        $this->gender = $gender;
    }

    /**
     * Returns Date of Birth.
     */
    public function getDateOfBirth(): ?\DateTime
    {
        return $this->dateOfBirth;
    }

    /**
     * Sets Date of Birth.
     *
     * @maps dateOfBirth
     * @factory \SwaggerScarecrowLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateOfBirth(?\DateTime $dateOfBirth): void
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): ?AddressFields
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @maps address
     */
    public function setAddress(?AddressFields $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Positions.
     *
     * @return string[]|null
     */
    public function getPositions(): ?array
    {
        return $this->positions;
    }

    /**
     * Sets Positions.
     *
     * @maps positions
     *
     * @param string[]|null $positions
     */
    public function setPositions(?array $positions): void
    {
        $this->positions = $positions;
    }

    /**
     * Returns Person Name Fields.
     */
    public function getPersonNameFields(): ?PersonNameFields
    {
        return $this->personNameFields;
    }

    /**
     * Sets Person Name Fields.
     *
     * @maps personNameFields
     */
    public function setPersonNameFields(?PersonNameFields $personNameFields): void
    {
        $this->personNameFields = $personNameFields;
    }

    /**
     * Returns Phone Fields.
     */
    public function getPhoneFields(): ?PhoneFields
    {
        return $this->phoneFields;
    }

    /**
     * Sets Phone Fields.
     *
     * @maps phoneFields
     */
    public function setPhoneFields(?PhoneFields $phoneFields): void
    {
        $this->phoneFields = $phoneFields;
    }

    /**
     * Returns Mobile Phone Fields.
     */
    public function getMobilePhoneFields(): ?PhoneFields
    {
        return $this->mobilePhoneFields;
    }

    /**
     * Sets Mobile Phone Fields.
     *
     * @maps mobilePhoneFields
     */
    public function setMobilePhoneFields(?PhoneFields $mobilePhoneFields): void
    {
        $this->mobilePhoneFields = $mobilePhoneFields;
    }

    /**
     * Returns Principal Identifier.
     */
    public function getPrincipalIdentifier(): ?string
    {
        return $this->principalIdentifier;
    }

    /**
     * Sets Principal Identifier.
     *
     * @maps principalIdentifier
     */
    public function setPrincipalIdentifier(?string $principalIdentifier): void
    {
        $this->principalIdentifier = $principalIdentifier;
    }

    /**
     * Returns Principal Owner Detail.
     */
    public function getPrincipalOwnerDetail(): ?PrincipalOwnerDetail
    {
        return $this->principalOwnerDetail;
    }

    /**
     * Sets Principal Owner Detail.
     *
     * @maps principalOwnerDetail
     */
    public function setPrincipalOwnerDetail(?PrincipalOwnerDetail $principalOwnerDetail): void
    {
        $this->principalOwnerDetail = $principalOwnerDetail;
    }

    /**
     * Returns Pesel.
     */
    public function getPesel(): ?string
    {
        return $this->pesel;
    }

    /**
     * Sets Pesel.
     *
     * @maps pesel
     */
    public function setPesel(?string $pesel): void
    {
        $this->pesel = $pesel;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']                 = $this->name;
        }
        if (isset($this->gender)) {
            $json['gender']               = $this->gender;
        }
        if (isset($this->dateOfBirth)) {
            $json['dateOfBirth']          = DateTimeHelper::toRfc3339DateTime($this->dateOfBirth);
        }
        if (isset($this->address)) {
            $json['address']              = $this->address;
        }
        if (isset($this->positions)) {
            $json['positions']            = $this->positions;
        }
        if (isset($this->personNameFields)) {
            $json['personNameFields']     = $this->personNameFields;
        }
        if (isset($this->phoneFields)) {
            $json['phoneFields']          = $this->phoneFields;
        }
        if (isset($this->mobilePhoneFields)) {
            $json['mobilePhoneFields']    = $this->mobilePhoneFields;
        }
        if (isset($this->principalIdentifier)) {
            $json['principalIdentifier']  = $this->principalIdentifier;
        }
        if (isset($this->principalOwnerDetail)) {
            $json['principalOwnerDetail'] = $this->principalOwnerDetail;
        }
        if (isset($this->pesel)) {
            $json['pesel']                = $this->pesel;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
