<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;
use SwaggerScarecrowLib\Utils\DateTimeHelper;

class CompanyIdentification implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $businessName;

    /**
     * @var string|null
     */
    private $registeredCompanyName;

    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $countryCode;

    /**
     * @var string|null
     */
    private $companyRegistrationNumber;

    /**
     * @var string|null
     */
    private $vatRegistrationNumber;

    /**
     * @var \DateTime|null
     */
    private $dateOfCompanyRegistration;

    /**
     * @var \DateTime|null
     */
    private $dateOfStartingOperation;

    /**
     * @var AddressFields|null
     */
    private $contactAddress;

    /**
     * @var string|null
     */
    private $ownerType;

    /**
     * @var string|null
     */
    private $taxIdType;

    /**
     * @var string|null
     */
    private $taxIdNumber;

    /**
     * @var string|null
     */
    private $fedTaxId;

    /**
     * @var \DateTime|null
     */
    private $certificationDate;

    /**
     * @var bool|null
     */
    private $customerCentricFlag;

    /**
     * @var string|null
     */
    private $mid;

    /**
     * Returns Business Name.
     */
    public function getBusinessName(): ?string
    {
        return $this->businessName;
    }

    /**
     * Sets Business Name.
     *
     * @maps businessName
     */
    public function setBusinessName(?string $businessName): void
    {
        $this->businessName = $businessName;
    }

    /**
     * Returns Registered Company Name.
     */
    public function getRegisteredCompanyName(): ?string
    {
        return $this->registeredCompanyName;
    }

    /**
     * Sets Registered Company Name.
     *
     * @maps registeredCompanyName
     */
    public function setRegisteredCompanyName(?string $registeredCompanyName): void
    {
        $this->registeredCompanyName = $registeredCompanyName;
    }

    /**
     * Returns Country.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Country Code.
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * Sets Country Code.
     *
     * @maps countryCode
     */
    public function setCountryCode(?string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    /**
     * Returns Company Registration Number.
     */
    public function getCompanyRegistrationNumber(): ?string
    {
        return $this->companyRegistrationNumber;
    }

    /**
     * Sets Company Registration Number.
     *
     * @maps companyRegistrationNumber
     */
    public function setCompanyRegistrationNumber(?string $companyRegistrationNumber): void
    {
        $this->companyRegistrationNumber = $companyRegistrationNumber;
    }

    /**
     * Returns Vat Registration Number.
     */
    public function getVatRegistrationNumber(): ?string
    {
        return $this->vatRegistrationNumber;
    }

    /**
     * Sets Vat Registration Number.
     *
     * @maps vatRegistrationNumber
     */
    public function setVatRegistrationNumber(?string $vatRegistrationNumber): void
    {
        $this->vatRegistrationNumber = $vatRegistrationNumber;
    }

    /**
     * Returns Date of Company Registration.
     */
    public function getDateOfCompanyRegistration(): ?\DateTime
    {
        return $this->dateOfCompanyRegistration;
    }

    /**
     * Sets Date of Company Registration.
     *
     * @maps dateOfCompanyRegistration
     * @factory \SwaggerScarecrowLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateOfCompanyRegistration(?\DateTime $dateOfCompanyRegistration): void
    {
        $this->dateOfCompanyRegistration = $dateOfCompanyRegistration;
    }

    /**
     * Returns Date of Starting Operation.
     */
    public function getDateOfStartingOperation(): ?\DateTime
    {
        return $this->dateOfStartingOperation;
    }

    /**
     * Sets Date of Starting Operation.
     *
     * @maps dateOfStartingOperation
     * @factory \SwaggerScarecrowLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateOfStartingOperation(?\DateTime $dateOfStartingOperation): void
    {
        $this->dateOfStartingOperation = $dateOfStartingOperation;
    }

    /**
     * Returns Contact Address.
     */
    public function getContactAddress(): ?AddressFields
    {
        return $this->contactAddress;
    }

    /**
     * Sets Contact Address.
     *
     * @maps contactAddress
     */
    public function setContactAddress(?AddressFields $contactAddress): void
    {
        $this->contactAddress = $contactAddress;
    }

    /**
     * Returns Owner Type.
     */
    public function getOwnerType(): ?string
    {
        return $this->ownerType;
    }

    /**
     * Sets Owner Type.
     *
     * @maps ownerType
     */
    public function setOwnerType(?string $ownerType): void
    {
        $this->ownerType = $ownerType;
    }

    /**
     * Returns Tax Id Type.
     */
    public function getTaxIdType(): ?string
    {
        return $this->taxIdType;
    }

    /**
     * Sets Tax Id Type.
     *
     * @maps taxIdType
     */
    public function setTaxIdType(?string $taxIdType): void
    {
        $this->taxIdType = $taxIdType;
    }

    /**
     * Returns Tax Id Number.
     */
    public function getTaxIdNumber(): ?string
    {
        return $this->taxIdNumber;
    }

    /**
     * Sets Tax Id Number.
     *
     * @maps taxIdNumber
     */
    public function setTaxIdNumber(?string $taxIdNumber): void
    {
        $this->taxIdNumber = $taxIdNumber;
    }

    /**
     * Returns Fed Tax Id.
     */
    public function getFedTaxId(): ?string
    {
        return $this->fedTaxId;
    }

    /**
     * Sets Fed Tax Id.
     *
     * @maps fedTaxId
     */
    public function setFedTaxId(?string $fedTaxId): void
    {
        $this->fedTaxId = $fedTaxId;
    }

    /**
     * Returns Certification Date.
     */
    public function getCertificationDate(): ?\DateTime
    {
        return $this->certificationDate;
    }

    /**
     * Sets Certification Date.
     *
     * @maps certificationDate
     * @factory \SwaggerScarecrowLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCertificationDate(?\DateTime $certificationDate): void
    {
        $this->certificationDate = $certificationDate;
    }

    /**
     * Returns Customer Centric Flag.
     */
    public function getCustomerCentricFlag(): ?bool
    {
        return $this->customerCentricFlag;
    }

    /**
     * Sets Customer Centric Flag.
     *
     * @maps customerCentricFlag
     */
    public function setCustomerCentricFlag(?bool $customerCentricFlag): void
    {
        $this->customerCentricFlag = $customerCentricFlag;
    }

    /**
     * Returns Mid.
     */
    public function getMid(): ?string
    {
        return $this->mid;
    }

    /**
     * Sets Mid.
     *
     * @maps mid
     */
    public function setMid(?string $mid): void
    {
        $this->mid = $mid;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->businessName)) {
            $json['businessName']              = $this->businessName;
        }
        if (isset($this->registeredCompanyName)) {
            $json['registeredCompanyName']     = $this->registeredCompanyName;
        }
        if (isset($this->country)) {
            $json['country']                   = $this->country;
        }
        if (isset($this->countryCode)) {
            $json['countryCode']               = $this->countryCode;
        }
        if (isset($this->companyRegistrationNumber)) {
            $json['companyRegistrationNumber'] = $this->companyRegistrationNumber;
        }
        if (isset($this->vatRegistrationNumber)) {
            $json['vatRegistrationNumber']     = $this->vatRegistrationNumber;
        }
        if (isset($this->dateOfCompanyRegistration)) {
            $json['dateOfCompanyRegistration'] = DateTimeHelper::toRfc3339DateTime($this->dateOfCompanyRegistration);
        }
        if (isset($this->dateOfStartingOperation)) {
            $json['dateOfStartingOperation']   = DateTimeHelper::toRfc3339DateTime($this->dateOfStartingOperation);
        }
        if (isset($this->contactAddress)) {
            $json['contactAddress']            = $this->contactAddress;
        }
        if (isset($this->ownerType)) {
            $json['ownerType']                 = $this->ownerType;
        }
        if (isset($this->taxIdType)) {
            $json['taxIdType']                 = $this->taxIdType;
        }
        if (isset($this->taxIdNumber)) {
            $json['taxIdNumber']               = $this->taxIdNumber;
        }
        if (isset($this->fedTaxId)) {
            $json['fedTaxId']                  = $this->fedTaxId;
        }
        if (isset($this->certificationDate)) {
            $json['certificationDate']         = DateTimeHelper::toRfc3339DateTime($this->certificationDate);
        }
        if (isset($this->customerCentricFlag)) {
            $json['customerCentricFlag']       = $this->customerCentricFlag;
        }
        if (isset($this->mid)) {
            $json['mid']                       = $this->mid;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
