<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class CompanyQueryResponse implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $responseId;

    /**
     * @var CompanyLightweight[]|null
     */
    private $searchResults;

    /**
     * @var string|null
     */
    private $error;

    /**
     * @var Timings|null
     */
    private $timings;

    /**
     * Returns Response Id.
     */
    public function getResponseId(): ?int
    {
        return $this->responseId;
    }

    /**
     * Sets Response Id.
     *
     * @maps responseId
     */
    public function setResponseId(?int $responseId): void
    {
        $this->responseId = $responseId;
    }

    /**
     * Returns Search Results.
     *
     * @return CompanyLightweight[]|null
     */
    public function getSearchResults(): ?array
    {
        return $this->searchResults;
    }

    /**
     * Sets Search Results.
     *
     * @maps searchResults
     *
     * @param CompanyLightweight[]|null $searchResults
     */
    public function setSearchResults(?array $searchResults): void
    {
        $this->searchResults = $searchResults;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps error
     */
    public function setError(?string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Timings.
     */
    public function getTimings(): ?Timings
    {
        return $this->timings;
    }

    /**
     * Sets Timings.
     *
     * @maps timings
     */
    public function setTimings(?Timings $timings): void
    {
        $this->timings = $timings;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->responseId)) {
            $json['responseId']    = $this->responseId;
        }
        if (isset($this->searchResults)) {
            $json['searchResults'] = $this->searchResults;
        }
        if (isset($this->error)) {
            $json['error']         = $this->error;
        }
        if (isset($this->timings)) {
            $json['timings']       = $this->timings;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
