<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class CreateGroupDocumentPacketRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $channelCode;

    /**
     * Returns Channel Code.
     * The unique identifier for the channel request is being executed under
     */
    public function getChannelCode(): ?string
    {
        return $this->channelCode;
    }

    /**
     * Sets Channel Code.
     * The unique identifier for the channel request is being executed under
     *
     * @maps channelCode
     */
    public function setChannelCode(?string $channelCode): void
    {
        $this->channelCode = $channelCode;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->channelCode)) {
            $json['channelCode'] = $this->channelCode;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
