<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class DocumentPacketData implements \JsonSerializable
{
    /**
     * @var ScarecrowApplication
     */
    private $scarecrowApplication;

    /**
     * @var string
     */
    private $language;

    /**
     * @var string|null
     */
    private $agreementId;

    /**
     * @var bool|null
     */
    private $isGroupedApplication;

    /**
     * @var bool|null
     */
    private $wetSigned;

    /**
     * @var CardVolume|null
     */
    private $cardVolume;

    /**
     * @var ProviderInfo
     */
    private $vendorInfo;

    /**
     * @var ActingIntermediaryInfo|null
     */
    private $actingIntermediaryInfo;

    /**
     * @var array<string,BankAccountAdditionalInfo>
     */
    private $bankAccountDetailsMap;

    /**
     * @var bool|null
     */
    private $isTaxExemptEquipment;

    /**
     * @var bool|null
     */
    private $talechEgiftOnly;

    /**
     * @var string
     */
    private $displayedCurrency;

    /**
     * @var AdditionalDescriptionInfo|null
     */
    private $additionalDescriptionInfo;

    /**
     * @var ValueAddedServices|null
     */
    private $additionalValueAddedServiceInfo;

    /**
     * @var AdditionalBusinessInfo|null
     */
    private $additionalBusinessInfo;

    /**
     * @var string|null
     */
    private $fundingType;

    /**
     * @var IntegratorSolutionInfo|null
     */
    private $integratorSolutionInfo;

    /**
     * @var AdditionalLeaseInfo|null
     */
    private $additionalLeaseInfo;

    /**
     * @var array<string,bool>|null
     */
    private $marketingDataConsentMap;

    /**
     * @var AdditionalSiteSurveyInfo|null
     */
    private $additionalSiteSurveyInfo;

    /**
     * @var array<string,string>|null
     */
    private $kycQuizStatusMap;

    /**
     * @var VarOtherDetails|null
     */
    private $varOtherDetails;

    /**
     * @var AdditionalCardPricingInfo|null
     */
    private $additionalCardPricingInfo;

    /**
     * @var SalesOfficeContact|null
     */
    private $salesOfficeContact;

    /**
     * @var SalesPersonContact|null
     */
    private $salesPersonContact;

    /**
     * @var AdditionalAuthPricingProgramInfo|null
     */
    private $additionalAuthPricingProgramInfo;

    /**
     * @var string|null
     */
    private $applicantEmail;

    /**
     * @var array<string,string>|null
     */
    private $partnerDocumentData;

    /**
     * @var int|null
     */
    private $applicationId;

    /**
     * @param ScarecrowApplication $scarecrowApplication
     * @param string $language
     * @param ProviderInfo $vendorInfo
     * @param array<string,BankAccountAdditionalInfo> $bankAccountDetailsMap
     * @param string $displayedCurrency
     */
    public function __construct(
        ScarecrowApplication $scarecrowApplication,
        string $language,
        ProviderInfo $vendorInfo,
        array $bankAccountDetailsMap,
        string $displayedCurrency
    ) {
        $this->scarecrowApplication = $scarecrowApplication;
        $this->language = $language;
        $this->vendorInfo = $vendorInfo;
        $this->bankAccountDetailsMap = $bankAccountDetailsMap;
        $this->displayedCurrency = $displayedCurrency;
    }

    /**
     * Returns Scarecrow Application.
     */
    public function getScarecrowApplication(): ScarecrowApplication
    {
        return $this->scarecrowApplication;
    }

    /**
     * Sets Scarecrow Application.
     *
     * @required
     * @maps scarecrowApplication
     */
    public function setScarecrowApplication(ScarecrowApplication $scarecrowApplication): void
    {
        $this->scarecrowApplication = $scarecrowApplication;
    }

    /**
     * Returns Language.
     * Language of document to be generated,  ISO 639-1 standard applies
     */
    public function getLanguage(): string
    {
        return $this->language;
    }

    /**
     * Sets Language.
     * Language of document to be generated,  ISO 639-1 standard applies
     *
     * @required
     * @maps language
     */
    public function setLanguage(string $language): void
    {
        $this->language = $language;
    }

    /**
     * Returns Agreement Id.
     * Merchant Id (MID)
     */
    public function getAgreementId(): ?string
    {
        return $this->agreementId;
    }

    /**
     * Sets Agreement Id.
     * Merchant Id (MID)
     *
     * @maps agreementId
     */
    public function setAgreementId(?string $agreementId): void
    {
        $this->agreementId = $agreementId;
    }

    /**
     * Returns Is Grouped Application.
     * Boolean flag indicating if document is of a group of applications, true if  YES, false if NO
     */
    public function getIsGroupedApplication(): ?bool
    {
        return $this->isGroupedApplication;
    }

    /**
     * Sets Is Grouped Application.
     * Boolean flag indicating if document is of a group of applications, true if  YES, false if NO
     *
     * @maps isGroupedApplication
     */
    public function setIsGroupedApplication(?bool $isGroupedApplication): void
    {
        $this->isGroupedApplication = $isGroupedApplication;
    }

    /**
     * Returns Wet Signed.
     * Boolean flag indicating if document is to be wet signed, true if  YES, false if NO
     */
    public function getWetSigned(): ?bool
    {
        return $this->wetSigned;
    }

    /**
     * Sets Wet Signed.
     * Boolean flag indicating if document is to be wet signed, true if  YES, false if NO
     *
     * @maps wetSigned
     */
    public function setWetSigned(?bool $wetSigned): void
    {
        $this->wetSigned = $wetSigned;
    }

    /**
     * Returns Card Volume.
     */
    public function getCardVolume(): ?CardVolume
    {
        return $this->cardVolume;
    }

    /**
     * Sets Card Volume.
     *
     * @maps cardVolume
     */
    public function setCardVolume(?CardVolume $cardVolume): void
    {
        $this->cardVolume = $cardVolume;
    }

    /**
     * Returns Vendor Info.
     */
    public function getVendorInfo(): ProviderInfo
    {
        return $this->vendorInfo;
    }

    /**
     * Sets Vendor Info.
     *
     * @required
     * @maps vendorInfo
     */
    public function setVendorInfo(ProviderInfo $vendorInfo): void
    {
        $this->vendorInfo = $vendorInfo;
    }

    /**
     * Returns Acting Intermediary Info.
     */
    public function getActingIntermediaryInfo(): ?ActingIntermediaryInfo
    {
        return $this->actingIntermediaryInfo;
    }

    /**
     * Sets Acting Intermediary Info.
     *
     * @maps actingIntermediaryInfo
     */
    public function setActingIntermediaryInfo(?ActingIntermediaryInfo $actingIntermediaryInfo): void
    {
        $this->actingIntermediaryInfo = $actingIntermediaryInfo;
    }

    /**
     * Returns Bank Account Details Map.
     * Application's additional bank account information. The valid keys are as follows: BILLING, DEPOSIT,
     * LEASE, CHARGEBACK
     *
     * @return array<string,BankAccountAdditionalInfo>
     */
    public function getBankAccountDetailsMap(): array
    {
        return $this->bankAccountDetailsMap;
    }

    /**
     * Sets Bank Account Details Map.
     * Application's additional bank account information. The valid keys are as follows: BILLING, DEPOSIT,
     * LEASE, CHARGEBACK
     *
     * @required
     * @maps bankAccountDetailsMap
     *
     * @param array<string,BankAccountAdditionalInfo> $bankAccountDetailsMap
     */
    public function setBankAccountDetailsMap(array $bankAccountDetailsMap): void
    {
        $this->bankAccountDetailsMap = $bankAccountDetailsMap;
    }

    /**
     * Returns Is Tax Exempt Equipment.
     * Flag indicating if equipment is to be considered tax exempt, true if exempt YES, false if NOT exept
     */
    public function getIsTaxExemptEquipment(): ?bool
    {
        return $this->isTaxExemptEquipment;
    }

    /**
     * Sets Is Tax Exempt Equipment.
     * Flag indicating if equipment is to be considered tax exempt, true if exempt YES, false if NOT exept
     *
     * @maps isTaxExemptEquipment
     */
    public function setIsTaxExemptEquipment(?bool $isTaxExemptEquipment): void
    {
        $this->isTaxExemptEquipment = $isTaxExemptEquipment;
    }

    /**
     * Returns Talech Egift Only.
     * Flag indicating if equipment is to Talech eGift, true if selected YES, false if NOT selected
     */
    public function getTalechEgiftOnly(): ?bool
    {
        return $this->talechEgiftOnly;
    }

    /**
     * Sets Talech Egift Only.
     * Flag indicating if equipment is to Talech eGift, true if selected YES, false if NOT selected
     *
     * @maps talechEgiftOnly
     */
    public function setTalechEgiftOnly(?bool $talechEgiftOnly): void
    {
        $this->talechEgiftOnly = $talechEgiftOnly;
    }

    /**
     * Returns Displayed Currency.
     * Application's currency, ISO 4217 standard applies
     */
    public function getDisplayedCurrency(): string
    {
        return $this->displayedCurrency;
    }

    /**
     * Sets Displayed Currency.
     * Application's currency, ISO 4217 standard applies
     *
     * @required
     * @maps displayedCurrency
     */
    public function setDisplayedCurrency(string $displayedCurrency): void
    {
        $this->displayedCurrency = $displayedCurrency;
    }

    /**
     * Returns Additional Description Info.
     */
    public function getAdditionalDescriptionInfo(): ?AdditionalDescriptionInfo
    {
        return $this->additionalDescriptionInfo;
    }

    /**
     * Sets Additional Description Info.
     *
     * @maps additionalDescriptionInfo
     */
    public function setAdditionalDescriptionInfo(?AdditionalDescriptionInfo $additionalDescriptionInfo): void
    {
        $this->additionalDescriptionInfo = $additionalDescriptionInfo;
    }

    /**
     * Returns Additional Value Added Service Info.
     */
    public function getAdditionalValueAddedServiceInfo(): ?ValueAddedServices
    {
        return $this->additionalValueAddedServiceInfo;
    }

    /**
     * Sets Additional Value Added Service Info.
     *
     * @maps additionalValueAddedServiceInfo
     */
    public function setAdditionalValueAddedServiceInfo(?ValueAddedServices $additionalValueAddedServiceInfo): void
    {
        $this->additionalValueAddedServiceInfo = $additionalValueAddedServiceInfo;
    }

    /**
     * Returns Additional Business Info.
     */
    public function getAdditionalBusinessInfo(): ?AdditionalBusinessInfo
    {
        return $this->additionalBusinessInfo;
    }

    /**
     * Sets Additional Business Info.
     *
     * @maps additionalBusinessInfo
     */
    public function setAdditionalBusinessInfo(?AdditionalBusinessInfo $additionalBusinessInfo): void
    {
        $this->additionalBusinessInfo = $additionalBusinessInfo;
    }

    /**
     * Returns Funding Type.
     * Application's funding type
     */
    public function getFundingType(): ?string
    {
        return $this->fundingType;
    }

    /**
     * Sets Funding Type.
     * Application's funding type
     *
     * @maps fundingType
     * @factory \SwaggerScarecrowLib\Models\FundingTypeEnum::checkValue
     */
    public function setFundingType(?string $fundingType): void
    {
        $this->fundingType = $fundingType;
    }

    /**
     * Returns Integrator Solution Info.
     */
    public function getIntegratorSolutionInfo(): ?IntegratorSolutionInfo
    {
        return $this->integratorSolutionInfo;
    }

    /**
     * Sets Integrator Solution Info.
     *
     * @maps integratorSolutionInfo
     */
    public function setIntegratorSolutionInfo(?IntegratorSolutionInfo $integratorSolutionInfo): void
    {
        $this->integratorSolutionInfo = $integratorSolutionInfo;
    }

    /**
     * Returns Additional Lease Info.
     */
    public function getAdditionalLeaseInfo(): ?AdditionalLeaseInfo
    {
        return $this->additionalLeaseInfo;
    }

    /**
     * Sets Additional Lease Info.
     *
     * @maps additionalLeaseInfo
     */
    public function setAdditionalLeaseInfo(?AdditionalLeaseInfo $additionalLeaseInfo): void
    {
        $this->additionalLeaseInfo = $additionalLeaseInfo;
    }

    /**
     * Returns Marketing Data Consent Map.
     * Application's consent form (POL). The valid keys are the numerical value of the marketing consent
     * option (1, 2, 3, etc)
     *
     * @return array<string,bool>|null
     */
    public function getMarketingDataConsentMap(): ?array
    {
        return $this->marketingDataConsentMap;
    }

    /**
     * Sets Marketing Data Consent Map.
     * Application's consent form (POL). The valid keys are the numerical value of the marketing consent
     * option (1, 2, 3, etc)
     *
     * @maps marketingDataConsentMap
     *
     * @param array<string,bool>|null $marketingDataConsentMap
     */
    public function setMarketingDataConsentMap(?array $marketingDataConsentMap): void
    {
        $this->marketingDataConsentMap = $marketingDataConsentMap;
    }

    /**
     * Returns Additional Site Survey Info.
     */
    public function getAdditionalSiteSurveyInfo(): ?AdditionalSiteSurveyInfo
    {
        return $this->additionalSiteSurveyInfo;
    }

    /**
     * Sets Additional Site Survey Info.
     *
     * @maps additionalSiteSurveyInfo
     */
    public function setAdditionalSiteSurveyInfo(?AdditionalSiteSurveyInfo $additionalSiteSurveyInfo): void
    {
        $this->additionalSiteSurveyInfo = $additionalSiteSurveyInfo;
    }

    /**
     * Returns Kyc Quiz Status Map.
     * Status results of the KCY check. Email to result map.
     *
     * @return array<string,string>|null
     */
    public function getKycQuizStatusMap(): ?array
    {
        return $this->kycQuizStatusMap;
    }

    /**
     * Sets Kyc Quiz Status Map.
     * Status results of the KCY check. Email to result map.
     *
     * @maps kycQuizStatusMap
     * @factory \SwaggerScarecrowLib\Models\KycQuizStatusMapEnum::checkValue
     *
     * @param array<string,string>|null $kycQuizStatusMap
     */
    public function setKycQuizStatusMap(?array $kycQuizStatusMap): void
    {
        $this->kycQuizStatusMap = $kycQuizStatusMap;
    }

    /**
     * Returns Var Other Details.
     */
    public function getVarOtherDetails(): ?VarOtherDetails
    {
        return $this->varOtherDetails;
    }

    /**
     * Sets Var Other Details.
     *
     * @maps varOtherDetails
     */
    public function setVarOtherDetails(?VarOtherDetails $varOtherDetails): void
    {
        $this->varOtherDetails = $varOtherDetails;
    }

    /**
     * Returns Additional Card Pricing Info.
     */
    public function getAdditionalCardPricingInfo(): ?AdditionalCardPricingInfo
    {
        return $this->additionalCardPricingInfo;
    }

    /**
     * Sets Additional Card Pricing Info.
     *
     * @maps additionalCardPricingInfo
     */
    public function setAdditionalCardPricingInfo(?AdditionalCardPricingInfo $additionalCardPricingInfo): void
    {
        $this->additionalCardPricingInfo = $additionalCardPricingInfo;
    }

    /**
     * Returns Sales Office Contact.
     */
    public function getSalesOfficeContact(): ?SalesOfficeContact
    {
        return $this->salesOfficeContact;
    }

    /**
     * Sets Sales Office Contact.
     *
     * @maps salesOfficeContact
     */
    public function setSalesOfficeContact(?SalesOfficeContact $salesOfficeContact): void
    {
        $this->salesOfficeContact = $salesOfficeContact;
    }

    /**
     * Returns Sales Person Contact.
     */
    public function getSalesPersonContact(): ?SalesPersonContact
    {
        return $this->salesPersonContact;
    }

    /**
     * Sets Sales Person Contact.
     *
     * @maps salesPersonContact
     */
    public function setSalesPersonContact(?SalesPersonContact $salesPersonContact): void
    {
        $this->salesPersonContact = $salesPersonContact;
    }

    /**
     * Returns Additional Auth Pricing Program Info.
     */
    public function getAdditionalAuthPricingProgramInfo(): ?AdditionalAuthPricingProgramInfo
    {
        return $this->additionalAuthPricingProgramInfo;
    }

    /**
     * Sets Additional Auth Pricing Program Info.
     *
     * @maps additionalAuthPricingProgramInfo
     */
    public function setAdditionalAuthPricingProgramInfo(
        ?AdditionalAuthPricingProgramInfo $additionalAuthPricingProgramInfo
    ): void {
        $this->additionalAuthPricingProgramInfo = $additionalAuthPricingProgramInfo;
    }

    /**
     * Returns Applicant Email.
     * Email address of applicant
     */
    public function getApplicantEmail(): ?string
    {
        return $this->applicantEmail;
    }

    /**
     * Sets Applicant Email.
     * Email address of applicant
     *
     * @maps applicantEmail
     */
    public function setApplicantEmail(?string $applicantEmail): void
    {
        $this->applicantEmail = $applicantEmail;
    }

    /**
     * Returns Partner Document Data.
     * The data for partner documents
     *
     * @return array<string,string>|null
     */
    public function getPartnerDocumentData(): ?array
    {
        return $this->partnerDocumentData;
    }

    /**
     * Sets Partner Document Data.
     * The data for partner documents
     *
     * @maps partnerDocumentData
     *
     * @param array<string,string>|null $partnerDocumentData
     */
    public function setPartnerDocumentData(?array $partnerDocumentData): void
    {
        $this->partnerDocumentData = $partnerDocumentData;
    }

    /**
     * Returns Application Id.
     * Application id
     */
    public function getApplicationId(): ?int
    {
        return $this->applicationId;
    }

    /**
     * Sets Application Id.
     * Application id
     *
     * @maps applicationId
     */
    public function setApplicationId(?int $applicationId): void
    {
        $this->applicationId = $applicationId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['scarecrowApplication']                 = $this->scarecrowApplication;
        $json['language']                             = $this->language;
        if (isset($this->agreementId)) {
            $json['agreementId']                      = $this->agreementId;
        }
        if (isset($this->isGroupedApplication)) {
            $json['isGroupedApplication']             = $this->isGroupedApplication;
        }
        if (isset($this->wetSigned)) {
            $json['wetSigned']                        = $this->wetSigned;
        }
        if (isset($this->cardVolume)) {
            $json['cardVolume']                       = $this->cardVolume;
        }
        $json['vendorInfo']                           = $this->vendorInfo;
        if (isset($this->actingIntermediaryInfo)) {
            $json['actingIntermediaryInfo']           = $this->actingIntermediaryInfo;
        }
        $json['bankAccountDetailsMap']                = $this->bankAccountDetailsMap;
        if (isset($this->isTaxExemptEquipment)) {
            $json['isTaxExemptEquipment']             = $this->isTaxExemptEquipment;
        }
        if (isset($this->talechEgiftOnly)) {
            $json['talechEgiftOnly']                  = $this->talechEgiftOnly;
        }
        $json['displayedCurrency']                    = $this->displayedCurrency;
        if (isset($this->additionalDescriptionInfo)) {
            $json['additionalDescriptionInfo']        = $this->additionalDescriptionInfo;
        }
        if (isset($this->additionalValueAddedServiceInfo)) {
            $json['additionalValueAddedServiceInfo']  = $this->additionalValueAddedServiceInfo;
        }
        if (isset($this->additionalBusinessInfo)) {
            $json['additionalBusinessInfo']           = $this->additionalBusinessInfo;
        }
        if (isset($this->fundingType)) {
            $json['fundingType']                      = FundingTypeEnum::checkValue($this->fundingType);
        }
        if (isset($this->integratorSolutionInfo)) {
            $json['integratorSolutionInfo']           = $this->integratorSolutionInfo;
        }
        if (isset($this->additionalLeaseInfo)) {
            $json['additionalLeaseInfo']              = $this->additionalLeaseInfo;
        }
        if (isset($this->marketingDataConsentMap)) {
            $json['marketingDataConsentMap']          = $this->marketingDataConsentMap;
        }
        if (isset($this->additionalSiteSurveyInfo)) {
            $json['additionalSiteSurveyInfo']         = $this->additionalSiteSurveyInfo;
        }
        if (isset($this->kycQuizStatusMap)) {
            $json['kycQuizStatusMap']                 = KycQuizStatusMapEnum::checkValue($this->kycQuizStatusMap);
        }
        if (isset($this->varOtherDetails)) {
            $json['varOtherDetails']                  = $this->varOtherDetails;
        }
        if (isset($this->additionalCardPricingInfo)) {
            $json['additionalCardPricingInfo']        = $this->additionalCardPricingInfo;
        }
        if (isset($this->salesOfficeContact)) {
            $json['salesOfficeContact']               = $this->salesOfficeContact;
        }
        if (isset($this->salesPersonContact)) {
            $json['salesPersonContact']               = $this->salesPersonContact;
        }
        if (isset($this->additionalAuthPricingProgramInfo)) {
            $json['additionalAuthPricingProgramInfo'] = $this->additionalAuthPricingProgramInfo;
        }
        if (isset($this->applicantEmail)) {
            $json['applicantEmail']                   = $this->applicantEmail;
        }
        if (isset($this->partnerDocumentData)) {
            $json['partnerDocumentData']              = $this->partnerDocumentData;
        }
        if (isset($this->applicationId)) {
            $json['applicationId']                    = $this->applicationId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
