<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class EframeRequestParams implements \JsonSerializable
{
    /**
     * @var string
     */
    private $uniqueId;

    /**
     * @var string
     */
    private $boardingId;

    /**
     * @var ScarecrowApplication
     */
    private $scarecrowApplication;

    /**
     * @param string $uniqueId
     * @param string $boardingId
     * @param ScarecrowApplication $scarecrowApplication
     */
    public function __construct(string $uniqueId, string $boardingId, ScarecrowApplication $scarecrowApplication)
    {
        $this->uniqueId = $uniqueId;
        $this->boardingId = $boardingId;
        $this->scarecrowApplication = $scarecrowApplication;
    }

    /**
     * Returns Unique Id.
     * Unique identifier of application submission, alphanumeric. Provided by the client.The uniqueId
     * must be wholly original and never repeated. The client's name followed by a millisecond timestamp
     * would work well.
     */
    public function getUniqueId(): string
    {
        return $this->uniqueId;
    }

    /**
     * Sets Unique Id.
     * Unique identifier of application submission, alphanumeric. Provided by the client.The uniqueId
     * must be wholly original and never repeated. The client's name followed by a millisecond timestamp
     * would work well.
     *
     * @required
     * @maps uniqueId
     */
    public function setUniqueId(string $uniqueId): void
    {
        $this->uniqueId = $uniqueId;
    }

    /**
     * Returns Boarding Id.
     * AWB (NA) or ApplicationID/MID (EU)
     */
    public function getBoardingId(): string
    {
        return $this->boardingId;
    }

    /**
     * Sets Boarding Id.
     * AWB (NA) or ApplicationID/MID (EU)
     *
     * @required
     * @maps boardingId
     */
    public function setBoardingId(string $boardingId): void
    {
        $this->boardingId = $boardingId;
    }

    /**
     * Returns Scarecrow Application.
     */
    public function getScarecrowApplication(): ScarecrowApplication
    {
        return $this->scarecrowApplication;
    }

    /**
     * Sets Scarecrow Application.
     *
     * @required
     * @maps scarecrowApplication
     */
    public function setScarecrowApplication(ScarecrowApplication $scarecrowApplication): void
    {
        $this->scarecrowApplication = $scarecrowApplication;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['uniqueId']             = $this->uniqueId;
        $json['boardingId']           = $this->boardingId;
        $json['scarecrowApplication'] = $this->scarecrowApplication;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
