<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class ElectronicCheckService implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $reportingFee;

    /**
     * @var string|null
     */
    private $reportingNumUsers;

    /**
     * @var AchCheckQuestions|null
     */
    private $achCheckQuestions;

    /**
     * Returns Reporting Fee.
     */
    public function getReportingFee(): ?float
    {
        return $this->reportingFee;
    }

    /**
     * Sets Reporting Fee.
     *
     * @maps reportingFee
     */
    public function setReportingFee(?float $reportingFee): void
    {
        $this->reportingFee = $reportingFee;
    }

    /**
     * Returns Reporting Num Users.
     */
    public function getReportingNumUsers(): ?string
    {
        return $this->reportingNumUsers;
    }

    /**
     * Sets Reporting Num Users.
     *
     * @maps reportingNumUsers
     */
    public function setReportingNumUsers(?string $reportingNumUsers): void
    {
        $this->reportingNumUsers = $reportingNumUsers;
    }

    /**
     * Returns Ach Check Questions.
     */
    public function getAchCheckQuestions(): ?AchCheckQuestions
    {
        return $this->achCheckQuestions;
    }

    /**
     * Sets Ach Check Questions.
     *
     * @maps achCheckQuestions
     */
    public function setAchCheckQuestions(?AchCheckQuestions $achCheckQuestions): void
    {
        $this->achCheckQuestions = $achCheckQuestions;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reportingFee)) {
            $json['reportingFee']      = $this->reportingFee;
        }
        if (isset($this->reportingNumUsers)) {
            $json['reportingNumUsers'] = $this->reportingNumUsers;
        }
        if (isset($this->achCheckQuestions)) {
            $json['achCheckQuestions'] = $this->achCheckQuestions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
