<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class ExecuteGroupDocumentPacketResponse implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $responseId;

    /**
     * @var string|null
     */
    private $error;

    /**
     * @var bool|null
     */
    private $successfulExecution;

    /**
     * Returns Response Id.
     */
    public function getResponseId(): ?int
    {
        return $this->responseId;
    }

    /**
     * Sets Response Id.
     *
     * @maps responseId
     */
    public function setResponseId(?int $responseId): void
    {
        $this->responseId = $responseId;
    }

    /**
     * Returns Error.
     * Error message from service
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     * Error message from service
     *
     * @maps error
     */
    public function setError(?string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Successful Execution.
     * Boolean flag indicating , true if execution successful, false if not
     */
    public function getSuccessfulExecution(): ?bool
    {
        return $this->successfulExecution;
    }

    /**
     * Sets Successful Execution.
     * Boolean flag indicating , true if execution successful, false if not
     *
     * @maps successfulExecution
     */
    public function setSuccessfulExecution(?bool $successfulExecution): void
    {
        $this->successfulExecution = $successfulExecution;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->responseId)) {
            $json['responseId']          = $this->responseId;
        }
        if (isset($this->error)) {
            $json['error']               = $this->error;
        }
        if (isset($this->successfulExecution)) {
            $json['successfulExecution'] = $this->successfulExecution;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
