<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class GetTerminalIdsRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $mid;

    /**
     * @var string|null
     */
    private $uniqueId;

    /**
     * Returns Mid.
     * Merchant Id
     */
    public function getMid(): ?string
    {
        return $this->mid;
    }

    /**
     * Sets Mid.
     * Merchant Id
     *
     * @maps mid
     */
    public function setMid(?string $mid): void
    {
        $this->mid = $mid;
    }

    /**
     * Returns Unique Id.
     * unique Id
     */
    public function getUniqueId(): ?string
    {
        return $this->uniqueId;
    }

    /**
     * Sets Unique Id.
     * unique Id
     *
     * @maps uniqueId
     */
    public function setUniqueId(?string $uniqueId): void
    {
        $this->uniqueId = $uniqueId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->mid)) {
            $json['mid']      = $this->mid;
        }
        if (isset($this->uniqueId)) {
            $json['uniqueId'] = $this->uniqueId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
