<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class IntegratorSolutionInfo implements \JsonSerializable
{
    /**
     * @var array<string,HealthCareEligibilityInfo>|null
     */
    private $healthCareEligibilitySelectionMap;

    /**
     * @var Payments|null
     */
    private $payments;

    /**
     * @var bool|null
     */
    private $hasEcsOnly;

    /**
     * @var string|null
     */
    private $sku;

    /**
     * Returns Health Care Eligibility Selection Map.
     * Map of health care service to related info. The valid keys are as follows: HEALTH_CARE_ELIGIBILITY,
     * HEALTH_CARE_CLAIMS, HEALTH_CARE_REMITTANCEHEALTH_CARE_ELIGIBILITY_AND_ESTIMATOR,
     * HEALTH_CARE_PATIENT_BILLING
     *
     * @return array<string,HealthCareEligibilityInfo>|null
     */
    public function getHealthCareEligibilitySelectionMap(): ?array
    {
        return $this->healthCareEligibilitySelectionMap;
    }

    /**
     * Sets Health Care Eligibility Selection Map.
     * Map of health care service to related info. The valid keys are as follows: HEALTH_CARE_ELIGIBILITY,
     * HEALTH_CARE_CLAIMS, HEALTH_CARE_REMITTANCEHEALTH_CARE_ELIGIBILITY_AND_ESTIMATOR,
     * HEALTH_CARE_PATIENT_BILLING
     *
     * @maps healthCareEligibilitySelectionMap
     *
     * @param array<string,HealthCareEligibilityInfo>|null $healthCareEligibilitySelectionMap
     */
    public function setHealthCareEligibilitySelectionMap(?array $healthCareEligibilitySelectionMap): void
    {
        $this->healthCareEligibilitySelectionMap = $healthCareEligibilitySelectionMap;
    }

    /**
     * Returns Payments.
     */
    public function getPayments(): ?Payments
    {
        return $this->payments;
    }

    /**
     * Sets Payments.
     *
     * @maps payments
     */
    public function setPayments(?Payments $payments): void
    {
        $this->payments = $payments;
    }

    /**
     * Returns Has Ecs Only.
     */
    public function getHasEcsOnly(): ?bool
    {
        return $this->hasEcsOnly;
    }

    /**
     * Sets Has Ecs Only.
     *
     * @maps hasEcsOnly
     */
    public function setHasEcsOnly(?bool $hasEcsOnly): void
    {
        $this->hasEcsOnly = $hasEcsOnly;
    }

    /**
     * Returns Sku.
     */
    public function getSku(): ?string
    {
        return $this->sku;
    }

    /**
     * Sets Sku.
     *
     * @maps sku
     */
    public function setSku(?string $sku): void
    {
        $this->sku = $sku;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->healthCareEligibilitySelectionMap)) {
            $json['healthCareEligibilitySelectionMap'] = $this->healthCareEligibilitySelectionMap;
        }
        if (isset($this->payments)) {
            $json['payments']                          = $this->payments;
        }
        if (isset($this->hasEcsOnly)) {
            $json['hasEcsOnly']                        = $this->hasEcsOnly;
        }
        if (isset($this->sku)) {
            $json['sku']                               = $this->sku;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
