<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class IntermediaryOwner implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $ownershipPct;

    /**
     * @var string|null
     */
    private $businessName;

    /**
     * @var Name|null
     */
    private $ownerName;

    /**
     * @var PhoneNumber|null
     */
    private $phone;

    /**
     * @var string|null
     */
    private $emailAddress;

    /**
     * @var Address|null
     */
    private $address;

    /**
     * Returns Ownership Pct.
     */
    public function getOwnershipPct(): ?string
    {
        return $this->ownershipPct;
    }

    /**
     * Sets Ownership Pct.
     *
     * @maps ownershipPct
     */
    public function setOwnershipPct(?string $ownershipPct): void
    {
        $this->ownershipPct = $ownershipPct;
    }

    /**
     * Returns Business Name.
     */
    public function getBusinessName(): ?string
    {
        return $this->businessName;
    }

    /**
     * Sets Business Name.
     *
     * @maps businessName
     */
    public function setBusinessName(?string $businessName): void
    {
        $this->businessName = $businessName;
    }

    /**
     * Returns Owner Name.
     */
    public function getOwnerName(): ?Name
    {
        return $this->ownerName;
    }

    /**
     * Sets Owner Name.
     *
     * @maps ownerName
     */
    public function setOwnerName(?Name $ownerName): void
    {
        $this->ownerName = $ownerName;
    }

    /**
     * Returns Phone.
     */
    public function getPhone(): ?PhoneNumber
    {
        return $this->phone;
    }

    /**
     * Sets Phone.
     *
     * @maps phone
     */
    public function setPhone(?PhoneNumber $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * Returns Email Address.
     */
    public function getEmailAddress(): ?string
    {
        return $this->emailAddress;
    }

    /**
     * Sets Email Address.
     *
     * @maps emailAddress
     */
    public function setEmailAddress(?string $emailAddress): void
    {
        $this->emailAddress = $emailAddress;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @maps address
     */
    public function setAddress(?Address $address): void
    {
        $this->address = $address;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ownershipPct)) {
            $json['ownershipPct'] = $this->ownershipPct;
        }
        if (isset($this->businessName)) {
            $json['businessName'] = $this->businessName;
        }
        if (isset($this->ownerName)) {
            $json['ownerName']    = $this->ownerName;
        }
        if (isset($this->phone)) {
            $json['phone']        = $this->phone;
        }
        if (isset($this->emailAddress)) {
            $json['emailAddress'] = $this->emailAddress;
        }
        if (isset($this->address)) {
            $json['address']      = $this->address;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
