<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use Exception;
use stdClass;
use SwaggerScarecrowLib\ApiHelper;

/**
 * Billing statement media type
 */
class MediaEnum
{
    public const DYNAMIC_MERCHANT_REPORTING = 'DYNAMIC_MERCHANT_REPORTING';

    public const HARD_COPY = 'HARD_COPY';

    public const EMAIL = 'EMAIL';

    public const FILE_TRANSFER = 'FILE_TRANSFER';

    public const NONE = 'NONE';

    private const _ALL_VALUES = [
        self::DYNAMIC_MERCHANT_REPORTING,
        self::HARD_COPY,
        self::EMAIL,
        self::FILE_TRANSFER,
        self::NONE,
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
