<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use Exception;
use stdClass;
use SwaggerScarecrowLib\ApiHelper;

/**
 * Network equipment will be connected to
 */
class NetworkEnum
{
    public const ELAVON = 'ELAVON';

    public const REDSYS = 'REDSYS';

    public const AXIS = 'AXIS';

    public const ADS_CHICAGO = 'ADS_CHICAGO';

    public const DCSI = 'DCSI';

    public const DELUXE_DATA = 'DELUXE_DATA';

    public const FIRST_DATA = 'FIRST_DATA';

    public const GCS = 'GCS';

    public const MDI = 'MDI';

    public const MERCHANT_LOCATION = 'MERCHANT_LOCATION';

    public const TELEMONEY = 'TELEMONEY';

    public const TPS = 'TPS';

    public const TSYS = 'TSYS';

    public const GLOBAL_NDC = 'GLOBAL_NDC';

    public const CEKAB = 'CEKAB';

    private const _ALL_VALUES = [
        self::ELAVON,
        self::REDSYS,
        self::AXIS,
        self::ADS_CHICAGO,
        self::DCSI,
        self::DELUXE_DATA,
        self::FIRST_DATA,
        self::GCS,
        self::MDI,
        self::MERCHANT_LOCATION,
        self::TELEMONEY,
        self::TPS,
        self::TSYS,
        self::GLOBAL_NDC,
        self::CEKAB,
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
