<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class PersonNameFields implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $personIdentifier;

    /**
     * @var string|null
     */
    private $simpleValue;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $middleName;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var string|null
     */
    private $suffix;

    /**
     * @var string|null
     */
    private $nickName;

    /**
     * Returns Person Identifier.
     */
    public function getPersonIdentifier(): ?string
    {
        return $this->personIdentifier;
    }

    /**
     * Sets Person Identifier.
     *
     * @maps personIdentifier
     */
    public function setPersonIdentifier(?string $personIdentifier): void
    {
        $this->personIdentifier = $personIdentifier;
    }

    /**
     * Returns Simple Value.
     */
    public function getSimpleValue(): ?string
    {
        return $this->simpleValue;
    }

    /**
     * Sets Simple Value.
     *
     * @maps simpleValue
     */
    public function setSimpleValue(?string $simpleValue): void
    {
        $this->simpleValue = $simpleValue;
    }

    /**
     * Returns Title.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns First Name.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     *
     * @maps firstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Middle Name.
     */
    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    /**
     * Sets Middle Name.
     *
     * @maps middleName
     */
    public function setMiddleName(?string $middleName): void
    {
        $this->middleName = $middleName;
    }

    /**
     * Returns Last Name.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     *
     * @maps lastName
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Suffix.
     */
    public function getSuffix(): ?string
    {
        return $this->suffix;
    }

    /**
     * Sets Suffix.
     *
     * @maps suffix
     */
    public function setSuffix(?string $suffix): void
    {
        $this->suffix = $suffix;
    }

    /**
     * Returns Nick Name.
     */
    public function getNickName(): ?string
    {
        return $this->nickName;
    }

    /**
     * Sets Nick Name.
     *
     * @maps nickName
     */
    public function setNickName(?string $nickName): void
    {
        $this->nickName = $nickName;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->personIdentifier)) {
            $json['personIdentifier'] = $this->personIdentifier;
        }
        if (isset($this->simpleValue)) {
            $json['simpleValue']      = $this->simpleValue;
        }
        if (isset($this->title)) {
            $json['title']            = $this->title;
        }
        if (isset($this->firstName)) {
            $json['firstName']        = $this->firstName;
        }
        if (isset($this->middleName)) {
            $json['middleName']       = $this->middleName;
        }
        if (isset($this->lastName)) {
            $json['lastName']         = $this->lastName;
        }
        if (isset($this->suffix)) {
            $json['suffix']           = $this->suffix;
        }
        if (isset($this->nickName)) {
            $json['nickName']         = $this->nickName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
