<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use Exception;
use stdClass;
use SwaggerScarecrowLib\ApiHelper;

/**
 * Method of card pricing to be applied
 */
class PricingMethodEnum
{
    public const CLEAR_AND_SIMPLE = 'CLEAR_AND_SIMPLE';

    public const TIERED_PRICING = 'TIERED_PRICING';

    public const INTERCHANGE_PLUS = 'INTERCHANGE_PLUS';

    public const FIXED = 'FIXED';

    public const ENHANCED_INTERCHANGE_PLUS = 'ENHANCED_INTERCHANGE_PLUS';

    public const SURCHARGE_PRICING = 'SURCHARGE_PRICING';

    public const INTERCHANGE_DIFFERENTIAL = 'INTERCHANGE_DIFFERENTIAL';

    public const FIXED_C4_PRICING = 'FIXED_C4_PRICING';

    public const FIXED_C4_PRICING_MERCHANT_MANAGED = 'FIXED_C4_PRICING_MERCHANT_MANAGED';

    public const ASSOCIATION = 'ASSOCIATION';

    public const FIXED_C4_PRICING_ELAVON_MANAGED = 'FIXED_C4_PRICING_ELAVON_MANAGED';

    private const _ALL_VALUES = [
        self::CLEAR_AND_SIMPLE,
        self::TIERED_PRICING,
        self::INTERCHANGE_PLUS,
        self::FIXED,
        self::ENHANCED_INTERCHANGE_PLUS,
        self::SURCHARGE_PRICING,
        self::INTERCHANGE_DIFFERENTIAL,
        self::FIXED_C4_PRICING,
        self::FIXED_C4_PRICING_MERCHANT_MANAGED,
        self::ASSOCIATION,
        self::FIXED_C4_PRICING_ELAVON_MANAGED,
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
