<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class RevenueShareInfo implements \JsonSerializable
{
    /**
     * @var string
     */
    private $secondarySalesPerson;

    /**
     * @var string
     */
    private $splitPercentage;

    /**
     * @param string $secondarySalesPerson
     * @param string $splitPercentage
     */
    public function __construct(string $secondarySalesPerson, string $splitPercentage)
    {
        $this->secondarySalesPerson = $secondarySalesPerson;
        $this->splitPercentage = $splitPercentage;
    }

    /**
     * Returns Secondary Sales Person.
     * Sales person representative code for secondary sales person
     */
    public function getSecondarySalesPerson(): string
    {
        return $this->secondarySalesPerson;
    }

    /**
     * Sets Secondary Sales Person.
     * Sales person representative code for secondary sales person
     *
     * @required
     * @maps secondarySalesPerson
     */
    public function setSecondarySalesPerson(string $secondarySalesPerson): void
    {
        $this->secondarySalesPerson = $secondarySalesPerson;
    }

    /**
     * Returns Split Percentage.
     * Percentage split allocated for secondary
     */
    public function getSplitPercentage(): string
    {
        return $this->splitPercentage;
    }

    /**
     * Sets Split Percentage.
     * Percentage split allocated for secondary
     *
     * @required
     * @maps splitPercentage
     */
    public function setSplitPercentage(string $splitPercentage): void
    {
        $this->splitPercentage = $splitPercentage;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['secondarySalesPerson'] = $this->secondarySalesPerson;
        $json['splitPercentage']      = $this->splitPercentage;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
