<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class SalesPersonContact implements \JsonSerializable
{
    /**
     * @var Name
     */
    private $name;

    /**
     * @var PhoneNumber
     */
    private $phone;

    /**
     * @var string
     */
    private $emailAddress;

    /**
     * @param Name $name
     * @param PhoneNumber $phone
     * @param string $emailAddress
     */
    public function __construct(Name $name, PhoneNumber $phone, string $emailAddress)
    {
        $this->name = $name;
        $this->phone = $phone;
        $this->emailAddress = $emailAddress;
    }

    /**
     * Returns Name.
     */
    public function getName(): Name
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(Name $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Phone.
     */
    public function getPhone(): PhoneNumber
    {
        return $this->phone;
    }

    /**
     * Sets Phone.
     *
     * @required
     * @maps phone
     */
    public function setPhone(PhoneNumber $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * Returns Email Address.
     * Contact email address of sales person
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }

    /**
     * Sets Email Address.
     * Contact email address of sales person
     *
     * @required
     * @maps emailAddress
     */
    public function setEmailAddress(string $emailAddress): void
    {
        $this->emailAddress = $emailAddress;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['name']         = $this->name;
        $json['phone']        = $this->phone;
        $json['emailAddress'] = $this->emailAddress;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
