<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class SignerResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $signerId;

    /**
     * @var string
     */
    private $signerUrl;

    /**
     * @param string $signerId
     * @param string $signerUrl
     */
    public function __construct(string $signerId, string $signerUrl)
    {
        $this->signerId = $signerId;
        $this->signerUrl = $signerUrl;
    }

    /**
     * Returns Signer Id.
     * The unique signer identifier
     */
    public function getSignerId(): string
    {
        return $this->signerId;
    }

    /**
     * Sets Signer Id.
     * The unique signer identifier
     *
     * @required
     * @maps signerId
     */
    public function setSignerId(string $signerId): void
    {
        $this->signerId = $signerId;
    }

    /**
     * Returns Signer Url.
     * The signer's URL
     */
    public function getSignerUrl(): string
    {
        return $this->signerUrl;
    }

    /**
     * Sets Signer Url.
     * The signer's URL
     *
     * @required
     * @maps signerUrl
     */
    public function setSignerUrl(string $signerUrl): void
    {
        $this->signerUrl = $signerUrl;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['signerId']  = $this->signerId;
        $json['signerUrl'] = $this->signerUrl;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
