<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class TerminalIdData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $terminalId;

    /**
     * @var string|null
     */
    private $userId;

    /**
     * @var string|null
     */
    private $pin;

    /**
     * @var string|null
     */
    private $errorText;

    /**
     * Returns Terminal Id.
     * Terminal Ids
     */
    public function getTerminalId(): ?string
    {
        return $this->terminalId;
    }

    /**
     * Sets Terminal Id.
     * Terminal Ids
     *
     * @maps terminalId
     */
    public function setTerminalId(?string $terminalId): void
    {
        $this->terminalId = $terminalId;
    }

    /**
     * Returns User Id.
     * Converge User Id
     */
    public function getUserId(): ?string
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     * Converge User Id
     *
     * @maps userId
     */
    public function setUserId(?string $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns Pin.
     * Converge PIN
     */
    public function getPin(): ?string
    {
        return $this->pin;
    }

    /**
     * Sets Pin.
     * Converge PIN
     *
     * @maps pin
     */
    public function setPin(?string $pin): void
    {
        $this->pin = $pin;
    }

    /**
     * Returns Error Text.
     * Any error that arose while processing results
     */
    public function getErrorText(): ?string
    {
        return $this->errorText;
    }

    /**
     * Sets Error Text.
     * Any error that arose while processing results
     *
     * @maps errorText
     */
    public function setErrorText(?string $errorText): void
    {
        $this->errorText = $errorText;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->terminalId)) {
            $json['terminalId'] = $this->terminalId;
        }
        if (isset($this->userId)) {
            $json['userId']     = $this->userId;
        }
        if (isset($this->pin)) {
            $json['pin']        = $this->pin;
        }
        if (isset($this->errorText)) {
            $json['errorText']  = $this->errorText;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
