<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class UploadDocumentResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $error;

    /**
     * @var string|null
     */
    private $docReferenceNumber;

    /**
     * @var UploadedDocumentDataResponse[]|null
     */
    private $uploadedDocumentsResponse;

    /**
     * Returns Error.
     * Error message from service
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     * Error message from service
     *
     * @maps error
     */
    public function setError(?string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Doc Reference Number.
     * Unique identifier of upload document response
     */
    public function getDocReferenceNumber(): ?string
    {
        return $this->docReferenceNumber;
    }

    /**
     * Sets Doc Reference Number.
     * Unique identifier of upload document response
     *
     * @maps docReferenceNumber
     */
    public function setDocReferenceNumber(?string $docReferenceNumber): void
    {
        $this->docReferenceNumber = $docReferenceNumber;
    }

    /**
     * Returns Uploaded Documents Response.
     * Listing of individual document upload statuses
     *
     * @return UploadedDocumentDataResponse[]|null
     */
    public function getUploadedDocumentsResponse(): ?array
    {
        return $this->uploadedDocumentsResponse;
    }

    /**
     * Sets Uploaded Documents Response.
     * Listing of individual document upload statuses
     *
     * @maps uploadedDocumentsResponse
     *
     * @param UploadedDocumentDataResponse[]|null $uploadedDocumentsResponse
     */
    public function setUploadedDocumentsResponse(?array $uploadedDocumentsResponse): void
    {
        $this->uploadedDocumentsResponse = $uploadedDocumentsResponse;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->error)) {
            $json['error']                     = $this->error;
        }
        if (isset($this->docReferenceNumber)) {
            $json['docReferenceNumber']        = $this->docReferenceNumber;
        }
        if (isset($this->uploadedDocumentsResponse)) {
            $json['uploadedDocumentsResponse'] = $this->uploadedDocumentsResponse;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
