<?php

declare(strict_types=1);

/*
 * SwaggerScarecrowLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerScarecrowLib\Models;

use stdClass;

class VarOtherDetails implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $varType;

    /**
     * @var string|null
     */
    private $vendor;

    /**
     * @var string|null
     */
    private $product;

    /**
     * @var string|null
     */
    private $version;

    /**
     * Returns Var Type.
     */
    public function getVarType(): ?string
    {
        return $this->varType;
    }

    /**
     * Sets Var Type.
     *
     * @maps varType
     * @factory \SwaggerScarecrowLib\Models\VarTypeEnum::checkValue
     */
    public function setVarType(?string $varType): void
    {
        $this->varType = $varType;
    }

    /**
     * Returns Vendor.
     */
    public function getVendor(): ?string
    {
        return $this->vendor;
    }

    /**
     * Sets Vendor.
     *
     * @maps vendor
     */
    public function setVendor(?string $vendor): void
    {
        $this->vendor = $vendor;
    }

    /**
     * Returns Product.
     */
    public function getProduct(): ?string
    {
        return $this->product;
    }

    /**
     * Sets Product.
     *
     * @maps product
     */
    public function setProduct(?string $product): void
    {
        $this->product = $product;
    }

    /**
     * Returns Version.
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * Sets Version.
     *
     * @maps version
     */
    public function setVersion(?string $version): void
    {
        $this->version = $version;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->varType)) {
            $json['varType'] = VarTypeEnum::checkValue($this->varType);
        }
        if (isset($this->vendor)) {
            $json['vendor']  = $this->vendor;
        }
        if (isset($this->product)) {
            $json['product'] = $this->product;
        }
        if (isset($this->version)) {
            $json['version'] = $this->version;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
